import {
  AdminUserRecord,
  AdminUserKpiMetric,
  RoleDistributionSlice,
  UserActivityItem,
} from './types';

export const ADMIN_USERS_KPIS: AdminUserKpiMetric[] = [
  {
    id: 'kpi-total',
    title: 'Total Admin Users',
    value: '18',
    change: '+12%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'total',
  },
  {
    id: 'kpi-active',
    title: 'Active Users',
    value: '16',
    change: '+6%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'active',
  },
  {
    id: 'kpi-inactive',
    title: 'Inactive Users',
    value: '2',
    change: '-33%',
    isPositive: false,
    periodText: 'vs last 30 days',
    type: 'inactive',
  },
  {
    id: 'kpi-suspended',
    title: 'Suspended Users',
    value: '0',
    change: '0%',
    isPositive: true,
    isNeutral: true,
    periodText: 'vs last 30 days',
    type: 'suspended',
  },
];

export const ROLE_DISTRIBUTION_DATA: RoleDistributionSlice[] = [
  {
    role: 'Super Admin',
    count: 1,
    percentage: 5.6,
    color: '#8B5CF6', // Purple
    hoverColor: '#7C3AED',
  },
  {
    role: 'Platform Manager',
    count: 4,
    percentage: 22.2,
    color: '#3B82F6', // Blue
    hoverColor: '#2563EB',
  },
  {
    role: 'Support Agent',
    count: 7,
    percentage: 38.9,
    color: '#F97316', // Orange / Amber
    hoverColor: '#EA580C',
  },
  {
    role: 'Finance Admin',
    count: 3,
    percentage: 16.7,
    color: '#EAB308', // Yellow
    hoverColor: '#CA8A04',
  },
  {
    role: 'Others',
    count: 3,
    percentage: 16.7,
    color: '#64748B', // Slate
    hoverColor: '#475569',
  },
];

export const RECENT_ACTIVITIES: UserActivityItem[] = [
  {
    id: 'act-1',
    title: 'New user added',
    description: 'Fahim Ahmed was added as Finance Admin',
    timestamp: 'Aug 14, 2026  10:20 AM',
    type: 'add',
  },
  {
    id: 'act-2',
    title: 'Role updated',
    description: "Mithila Khan's role changed to Support Agent",
    timestamp: 'Aug 13, 2026  04:35 PM',
    type: 'update',
  },
  {
    id: 'act-3',
    title: 'User deactivated',
    description: 'Jannatul Ferdous was deactivated',
    timestamp: 'Aug 13, 2026  11:10 AM',
    type: 'deactivate',
  },
  {
    id: 'act-4',
    title: 'Password reset',
    description: 'Password reset for Nahid Hasan',
    timestamp: 'Aug 12, 2026  09:25 AM',
    type: 'reset',
  },
  {
    id: 'act-5',
    title: '2FA enabled',
    description: 'Aminur Rahman enabled Two-Factor Auth',
    timestamp: 'Aug 12, 2026  08:15 AM',
    type: '2fa',
  },
];

export const INITIAL_ADMIN_USERS: AdminUserRecord[] = [
  {
    id: 'usr-1',
    name: 'Super Admin',
    email: 'superadmin@easyco.com',
    initials: 'SA',
    avatarBgColor: 'bg-emerald-600',
    role: 'Super Admin',
    status: 'Active',
    lastLoginDate: 'Aug 14, 2026',
    lastLoginTime: '10:32 AM',
    twoFactorAuth: true,
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    phone: '+880 1700-000001',
    department: 'Platform Operations',
    permissionsCount: 42,
  },
  {
    id: 'usr-2',
    name: 'Platform Manager',
    email: 'pmanager@easyco.com',
    initials: 'PA',
    avatarBgColor: 'bg-blue-600',
    role: 'Platform Manager',
    status: 'Active',
    lastLoginDate: 'Aug 14, 2026',
    lastLoginTime: '09:18 AM',
    twoFactorAuth: true,
    createdAtDate: 'Feb 02, 2024',
    createdAtTime: '11:20 AM',
    phone: '+880 1711-223344',
    department: 'Product Management',
    permissionsCount: 35,
  },
  {
    id: 'usr-3',
    name: 'Rahim Hossain',
    email: 'rahim.hossain@easyco.com',
    initials: 'RH',
    avatarBgColor: 'bg-slate-700',
    role: 'Platform Manager',
    status: 'Active',
    lastLoginDate: 'Aug 13, 2026',
    lastLoginTime: '06:45 PM',
    twoFactorAuth: true,
    createdAtDate: 'Feb 15, 2024',
    createdAtTime: '02:30 PM',
    phone: '+880 1812-334455',
    department: 'Engineering',
    permissionsCount: 35,
  },
  {
    id: 'usr-4',
    name: 'Sadia Ahmed',
    email: 'sadia.ahmed@easyco.com',
    initials: 'SA',
    avatarBgColor: 'bg-purple-600',
    role: 'Support Agent',
    status: 'Active',
    lastLoginDate: 'Aug 13, 2026',
    lastLoginTime: '03:10 PM',
    twoFactorAuth: true,
    createdAtDate: 'Mar 05, 2024',
    createdAtTime: '10:05 AM',
    phone: '+880 1913-667788',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  {
    id: 'usr-5',
    name: 'Fahim Ahmed',
    email: 'fahim.ahmed@easyco.com',
    initials: 'FA',
    avatarBgColor: 'bg-amber-600',
    role: 'Finance Admin',
    status: 'Active',
    lastLoginDate: 'Aug 12, 2026',
    lastLoginTime: '11:05 AM',
    twoFactorAuth: false,
    createdAtDate: 'Mar 20, 2024',
    createdAtTime: '01:40 PM',
    phone: '+880 1614-223344',
    department: 'Finance & Payouts',
    permissionsCount: 22,
  },
  {
    id: 'usr-6',
    name: 'Jannatul Ferdous',
    email: 'jannat.ferdous@easyco.com',
    initials: 'SA',
    avatarBgColor: 'bg-teal-600',
    role: 'Support Agent',
    status: 'Inactive',
    lastLoginDate: 'Jul 28, 2026',
    lastLoginTime: '04:22 PM',
    twoFactorAuth: true,
    createdAtDate: 'Apr 10, 2024',
    createdAtTime: '09:30 AM',
    phone: '+880 1515-778899',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  {
    id: 'usr-7',
    name: 'Nahid Hasan',
    email: 'nahid.hasan@easyco.com',
    initials: 'NH',
    avatarBgColor: 'bg-slate-700',
    role: 'Platform Manager',
    status: 'Inactive',
    lastLoginDate: 'Jul 15, 2026',
    lastLoginTime: '10:11 AM',
    twoFactorAuth: false,
    createdAtDate: 'Apr 18, 2024',
    createdAtTime: '11:45 AM',
    phone: '+880 1718-990011',
    department: 'Product Management',
    permissionsCount: 35,
  },
  {
    id: 'usr-8',
    name: 'Aminur Rahman',
    email: 'aminur.rahman@easyco.com',
    initials: 'AR',
    avatarBgColor: 'bg-rose-600',
    role: 'Finance Admin',
    status: 'Active',
    lastLoginDate: 'Aug 14, 2026',
    lastLoginTime: '08:15 AM',
    twoFactorAuth: true,
    createdAtDate: 'May 01, 2024',
    createdAtTime: '02:20 PM',
    phone: '+880 1819-445566',
    department: 'Finance & Payouts',
    permissionsCount: 22,
  },
  {
    id: 'usr-9',
    name: 'Mithila Khan',
    email: 'mithila.khan@easyco.com',
    initials: 'MK',
    avatarBgColor: 'bg-emerald-600',
    role: 'Support Agent',
    status: 'Active',
    lastLoginDate: 'Aug 11, 2026',
    lastLoginTime: '06:45 PM',
    twoFactorAuth: true,
    createdAtDate: 'May 18, 2024',
    createdAtTime: '03:10 PM',
    phone: '+880 1912-889900',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  {
    id: 'usr-10',
    name: 'Tanvir Shuvo',
    email: 'tanvir.shuvo@easyco.com',
    initials: 'TS',
    avatarBgColor: 'bg-purple-600',
    role: 'Support Agent',
    status: 'Active',
    lastLoginDate: 'Aug 10, 2026',
    lastLoginTime: '09:22 AM',
    twoFactorAuth: false,
    createdAtDate: 'Jun 02, 2024',
    createdAtTime: '09:50 AM',
    phone: '+880 1713-112233',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  // Page 2 users
  {
    id: 'usr-11',
    name: 'Alex Rivera',
    email: 'alex.rivera@easyco.com',
    initials: 'AR',
    avatarBgColor: 'bg-blue-600',
    role: 'Security Admin',
    status: 'Active',
    lastLoginDate: 'Aug 09, 2026',
    lastLoginTime: '11:40 AM',
    twoFactorAuth: true,
    createdAtDate: 'Jun 15, 2024',
    createdAtTime: '10:00 AM',
    phone: '+880 1714-223344',
    department: 'Security & Compliance',
    permissionsCount: 40,
  },
  {
    id: 'usr-12',
    name: 'Sarah Jenkins',
    email: 'sarah.j@easyco.com',
    initials: 'SJ',
    avatarBgColor: 'bg-emerald-600',
    role: 'Super Admin',
    status: 'Active',
    lastLoginDate: 'Aug 08, 2026',
    lastLoginTime: '04:15 PM',
    twoFactorAuth: true,
    createdAtDate: 'Jun 20, 2024',
    createdAtTime: '02:45 PM',
    phone: '+880 1715-334455',
    department: 'Platform Operations',
    permissionsCount: 42,
  },
  {
    id: 'usr-13',
    name: 'David Miller',
    email: 'david.m@easyco.com',
    initials: 'DM',
    avatarBgColor: 'bg-slate-700',
    role: 'Others',
    status: 'Active',
    lastLoginDate: 'Aug 07, 2026',
    lastLoginTime: '01:20 PM',
    twoFactorAuth: true,
    createdAtDate: 'Jul 01, 2024',
    createdAtTime: '09:10 AM',
    phone: '+880 1716-445566',
    department: 'DevOps',
    permissionsCount: 28,
  },
  {
    id: 'usr-14',
    name: 'Kazi Masud',
    email: 'kazi.masud@easyco.com',
    initials: 'KM',
    avatarBgColor: 'bg-amber-600',
    role: 'Support Agent',
    status: 'Active',
    lastLoginDate: 'Aug 06, 2026',
    lastLoginTime: '03:50 PM',
    twoFactorAuth: false,
    createdAtDate: 'Jul 10, 2024',
    createdAtTime: '11:15 AM',
    phone: '+880 1717-556677',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  {
    id: 'usr-15',
    name: 'Shahriar Kabir',
    email: 'shahriar@easyco.com',
    initials: 'SK',
    avatarBgColor: 'bg-purple-600',
    role: 'Finance Admin',
    status: 'Active',
    lastLoginDate: 'Aug 05, 2026',
    lastLoginTime: '10:05 AM',
    twoFactorAuth: true,
    createdAtDate: 'Jul 15, 2024',
    createdAtTime: '04:30 PM',
    phone: '+880 1718-667788',
    department: 'Finance & Payouts',
    permissionsCount: 22,
  },
  {
    id: 'usr-16',
    name: 'Mehedi Hasan',
    email: 'mehedi.h@easyco.com',
    initials: 'MH',
    avatarBgColor: 'bg-teal-600',
    role: 'Support Agent',
    status: 'Active',
    lastLoginDate: 'Aug 04, 2026',
    lastLoginTime: '08:45 AM',
    twoFactorAuth: true,
    createdAtDate: 'Jul 22, 2024',
    createdAtTime: '01:20 PM',
    phone: '+880 1719-778899',
    department: 'Customer Support',
    permissionsCount: 18,
  },
  {
    id: 'usr-17',
    name: 'Anika Tabassum',
    email: 'anika.t@easyco.com',
    initials: 'AT',
    avatarBgColor: 'bg-rose-600',
    role: 'Others',
    status: 'Active',
    lastLoginDate: 'Aug 03, 2026',
    lastLoginTime: '05:30 PM',
    twoFactorAuth: false,
    createdAtDate: 'Aug 01, 2024',
    createdAtTime: '10:45 AM',
    phone: '+880 1720-889900',
    department: 'Marketing Ops',
    permissionsCount: 15,
  },
  {
    id: 'usr-18',
    name: 'Nusrat Jahan',
    email: 'nusrat.j@easyco.com',
    initials: 'NJ',
    avatarBgColor: 'bg-blue-600',
    role: 'Others',
    status: 'Active',
    lastLoginDate: 'Aug 02, 2026',
    lastLoginTime: '12:15 PM',
    twoFactorAuth: true,
    createdAtDate: 'Aug 05, 2024',
    createdAtTime: '03:00 PM',
    phone: '+880 1721-990011',
    department: 'Quality Assurance',
    permissionsCount: 15,
  },
];
