import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsEnum, IsBoolean, IsArray, ValidateNested, IsInt, Min } from 'class-validator';
import { Type } from 'class-transformer';
import { AttributeType } from '../enums/attribute-type.enum';

export class AttributeOptionDto {
  @ApiProperty({ example: 'Black', description: 'Option label' })
  @IsNotEmpty()
  @IsString()
  label: string;

  @ApiProperty({ example: 'black', description: 'Option value' })
  @IsNotEmpty()
  @IsString()
  value: string;

  @ApiPropertyOptional({ example: 0, description: 'Sort order' })
  @IsOptional()
  @IsInt()
  @Min(0)
  sortOrder?: number;
}

export class CreateAttributeDto {
  @ApiProperty({ example: 'RAM', description: 'Attribute display name' })
  @IsNotEmpty({ message: 'Attribute name is required' })
  @IsString()
  name: string;

  @ApiPropertyOptional({ example: 'ram', description: 'Custom machine key (autogenerated from name if omitted)' })
  @IsOptional()
  @IsString()
  key?: string;

  @ApiProperty({ enum: AttributeType, example: AttributeType.SELECT, description: 'Attribute type' })
  @IsEnum(AttributeType)
  type: AttributeType;

  @ApiPropertyOptional({ example: 'Device memory capacity', description: 'Description' })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ example: false, description: 'Is mandatory for products' })
  @IsOptional()
  @IsBoolean()
  isRequired?: boolean;

  @ApiPropertyOptional({ example: true, description: 'Can be used for storefront filtering' })
  @IsOptional()
  @IsBoolean()
  isFilterable?: boolean;

  @ApiPropertyOptional({ example: false, description: 'Can be used as variant dimension' })
  @IsOptional()
  @IsBoolean()
  isVariantOption?: boolean;

  @ApiPropertyOptional({ type: [AttributeOptionDto], description: 'Predefined options for SELECT and MULTI_SELECT types' })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AttributeOptionDto)
  options?: AttributeOptionDto[];
}
