import {
  SubscriptionKpiCardItem,
  RevenueDataPoint,
  NewVsCancelledPoint,
  DonutSegment,
  FunnelMetric,
  FailedPaymentRecord,
  SubscriptionRecord,
} from './types';

export const SUBSCRIPTION_KPIS: SubscriptionKpiCardItem[] = [
  {
    id: 'active-subscriptions',
    title: 'Active Subscriptions',
    value: '2,466',
    change: '9.8%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'active',
  },
  {
    id: 'trial-subscriptions',
    title: 'Trial Subscriptions',
    value: '82',
    change: '5.7%',
    isPositive: false,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'trial',
  },
  {
    id: 'expired',
    title: 'Expired',
    value: '36',
    change: '2.8%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'expired',
  },
  {
    id: 'cancelled',
    title: 'Cancelled (This Month)',
    value: '78',
    change: '14.6%',
    isPositive: false,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'cancelled',
  },
  {
    id: 'mrr',
    title: 'MRR (Monthly)',
    value: '৳18,40,000',
    change: '14.6%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'mrr',
  },
  {
    id: 'arr',
    title: 'ARR (Yearly)',
    value: '৳2,20,80,000',
    change: '16.3%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'arr',
  },
];

export const REVENUE_CHART_DATA: RevenueDataPoint[] = [
  { date: 'Aug 8', mrr: 1200000, arr: 600000 },
  { date: 'Aug 9', mrr: 1450000, arr: 850000 },
  { date: 'Aug 10', mrr: 1600000, arr: 750000 },
  { date: 'Aug 11', mrr: 1520000, arr: 900000 },
  { date: 'Aug 12', mrr: 1800000, arr: 1100000 },
  { date: 'Aug 13', mrr: 1650000, arr: 980000 },
  { date: 'Aug 14', mrr: 1950000, arr: 1300000 },
];

export const NEW_VS_CANCELLED_DATA: NewVsCancelledPoint[] = [
  { date: 'Aug 8', newCount: 42, cancelledCount: 12 },
  { date: 'Aug 9', newCount: 50, cancelledCount: 16 },
  { date: 'Aug 10', newCount: 65, cancelledCount: 22 },
  { date: 'Aug 11', newCount: 58, cancelledCount: 18 },
  { date: 'Aug 12', newCount: 72, cancelledCount: 25 },
  { date: 'Aug 13', newCount: 60, cancelledCount: 20 },
  { date: 'Aug 14', newCount: 80, cancelledCount: 30 },
];

export const STATUS_BREAKDOWN: DonutSegment[] = [
  { name: 'Active', value: 2466, percentage: '75.8%', color: '#10B981' },
  { name: 'Trial', value: 82, percentage: '3.2%', color: '#64748B' },
  { name: 'Expired', value: 36, percentage: '1.4%', color: '#F59E0B' },
  { name: 'Cancelled', value: 78, percentage: '2.4%', color: '#EF4444' },
  { name: 'Paused', value: 46, percentage: '1.8%', color: '#94A3B8' },
  { name: 'Other', value: 12, percentage: '-', color: '#8B5CF6' },
];

export const PLAN_BREAKDOWN: DonutSegment[] = [
  { name: 'Active', value: 2460, percentage: '73.8%', color: '#10B981' },
  { name: 'Trial', value: 842, percentage: '32.6%', color: '#3B82F6' },
  { name: 'Expired', value: 36, percentage: '1.4%', color: '#F59E0B' },
  { name: 'Enterprise', value: 56, percentage: '2.2%', color: '#8B5CF6' },
  { name: 'Trial', value: 46, percentage: '2.4%', color: '#94A3B8' },
];

export const CONVERSION_FUNNEL_METRICS: FunnelMetric[] = [
  { label: 'Trial Started', value: '214', percentage: 100, color: '#10B981' },
  { label: 'Trial to Paid', value: '136 (63.6%)', percentage: 63.6, color: '#10B981' },
  { label: 'Paid Subscriptions', value: '78 (36.4%)', percentage: 36.4, color: '#10B981' },
  { label: 'Churned', value: '78 (1.6%)', percentage: 12, color: '#EF4444' },
];

export const FAILED_PAYMENTS: FailedPaymentRecord[] = [
  {
    id: 'fp-1',
    storeName: 'ABC Fashion Store',
    subId: 'SUB-0002',
    initials: 'AF',
    avatarBg: 'bg-rose-400',
    amount: '৳2,500',
    date: 'Aug 14, 2026',
  },
  {
    id: 'fp-2',
    storeName: 'Gadget Hub',
    subId: 'SUB-0003',
    initials: 'GH',
    avatarBg: 'bg-indigo-400',
    amount: '৳5,000',
    date: 'Aug 13, 2026',
  },
  {
    id: 'fp-3',
    storeName: 'Book Haven',
    subId: 'SUB-0004',
    initials: 'HM',
    avatarBg: 'bg-teal-400',
    amount: '৳2,500',
    date: 'Aug 13, 2026',
  },
];

export const INITIAL_SUBSCRIPTIONS: SubscriptionRecord[] = [
  {
    id: 'sub-1',
    codeId: 'SUB-0001',
    initials: 'US',
    avatarBg: 'bg-slate-900',
    domain: 'urbanstyle.easyco.com',
    storeName: 'Urban Style Store',
    merchantName: 'Rahim Hossain',
    plan: 'Business',
    status: 'Active',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Sep 14, 2026',
      subtext: 'in 31 days',
    },
    mrr: '৳5,000',
    amount: '৳5,000',
  },
  {
    id: 'sub-2',
    codeId: 'SUB-0002',
    initials: 'AF',
    avatarBg: 'bg-rose-400',
    domain: 'abcfashion.easyco.com',
    storeName: 'ABC Fashion Store',
    merchantName: 'Karim Ahmed',
    plan: 'Growth',
    status: 'Active',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Sep 14, 2026',
      subtext: 'in 31 days',
    },
    mrr: '৳2,500',
    amount: '৳2,500',
  },
  {
    id: 'sub-3',
    codeId: 'SUB-0003',
    initials: 'GH',
    avatarBg: 'bg-indigo-400',
    domain: 'gadgethub.easyco.com',
    storeName: 'Gadget Hub',
    merchantName: 'Mim Akter',
    plan: 'Business',
    status: 'Active',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Sep 13, 2026',
      subtext: 'in 30 days',
    },
    mrr: '৳5,000',
    amount: '৳5,000',
  },
  {
    id: 'sub-4',
    codeId: 'SUB-0004',
    initials: 'BH',
    avatarBg: 'bg-amber-500',
    domain: 'bookhaven.easyco.com',
    storeName: 'Book Haven',
    merchantName: 'Sabir Islam',
    plan: 'Growth',
    status: 'Active',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Sep 13, 2026',
      subtext: 'in 30 days',
    },
    mrr: '৳2,500',
    amount: '৳2,500',
  },
  {
    id: 'sub-5',
    codeId: 'SUB-0005',
    initials: 'DE',
    avatarBg: 'bg-amber-400',
    domain: 'dailyessentials.easyco.com',
    storeName: 'Daily Essentials',
    merchantName: 'Sabir Islam',
    plan: 'Starter',
    status: 'Active',
    billingCycle: 'Annual',
    nextBillingDate: {
      date: 'Jul 13, 2027',
      subtext: 'in 333 days',
    },
    mrr: '৳1,000',
    amount: '৳12,000',
  },
  {
    id: 'sub-6',
    codeId: 'SUB-0006',
    initials: 'TS',
    avatarBg: 'bg-slate-400',
    domain: 'techsolution.easyco.com',
    storeName: 'Tech Solution',
    merchantName: 'Nahid Hasan',
    plan: 'Starter',
    status: 'Trial',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Sep 13, 2027',
      subtext: 'in 333 days',
    },
    mrr: '৳0',
    amount: '৳0',
  },
  {
    id: 'sub-7',
    codeId: 'SUB-0007',
    initials: 'HM',
    avatarBg: 'bg-teal-400',
    domain: 'homemart.easyco.com',
    storeName: 'Home Mart',
    merchantName: 'Riyan Ahmed',
    plan: 'Growth',
    status: 'Suspended',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Aug 12, 2026',
      subtext: 'Expired',
    },
    mrr: '৳0',
    amount: '৳0',
  },
  {
    id: 'sub-8',
    codeId: 'SUB-0008',
    initials: 'FS',
    avatarBg: 'bg-rose-500',
    domain: 'freshshop.easyco.com',
    storeName: 'FreshShop',
    merchantName: 'Tonu Rahman',
    plan: 'Starter',
    status: 'Cancelled',
    billingCycle: 'Monthly',
    nextBillingDate: {
      date: 'Aug 10, 2026',
      subtext: 'Cancelled',
    },
    mrr: '৳0',
    amount: '৳0',
  },
];
