import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { LeadEntity, LeadStageEnum, LeadSourceEnum } from '../entities/lead.entity';

@Injectable()
export class SeedLeadsService {
  constructor(
    @InjectRepository(LeadEntity)
    private readonly leadRepository: Repository<LeadEntity>,
  ) {}

  async execute(tenantId: string, storeId?: string): Promise<LeadEntity[]> {
    const seedData = [
      {
        tenantId,
        storeId,
        name: 'Tanvir Ahmed',
        companyName: 'Apex Logistics Ltd',
        phone: '01711223344',
        email: 'tanvir.ahmed@apex.com.bd',
        source: LeadSourceEnum.WHATSAPP,
        stage: LeadStageEnum.NEW,
        estimatedValue: 45000,
        leadScore: 85,
        notes: 'Interested in bulk corporate polo shirts (150 pcs). Requested fabric sample and color chart.',
        nextFollowUpAt: new Date(Date.now() + 3 * 3600 * 1000),
        followUpNote: 'Send fabric sample photos on WhatsApp at 4 PM',
        followUpStatus: 'PENDING',
        tags: ['Corporate', 'Bulk Order', 'High Value'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Nusrat Jahan',
        companyName: 'Chic Boutique',
        phone: '01819887766',
        email: 'nusrat@chicboutique.bd',
        source: LeadSourceEnum.FACEBOOK,
        stage: LeadStageEnum.NEW,
        estimatedValue: 24000,
        leadScore: 78,
        notes: 'Inquired about wholesale designer silk sarees for Eid collection. Budget flexible.',
        nextFollowUpAt: new Date(Date.now() + 24 * 3600 * 1000),
        followUpNote: 'Call back to confirm catalog selection',
        followUpStatus: 'PENDING',
        tags: ['Retailer', 'Social Inquiry'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Mahmudul Hasan',
        companyName: 'Hasan Electronics',
        phone: '01755667788',
        email: 'hasan@hasanelectro.com',
        source: LeadSourceEnum.PHONE_CALL,
        stage: LeadStageEnum.CONTACTED,
        estimatedValue: 65000,
        leadScore: 82,
        notes: 'Spoke over phone. Needs 50 units for store restocking by end of next week.',
        nextFollowUpAt: new Date(Date.now() + 5 * 3600 * 1000),
        followUpNote: 'Email formal quotation and delivery terms',
        followUpStatus: 'PENDING',
        tags: ['Wholesale', 'Urgent Delivery'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Farzana Yasmin',
        companyName: 'Organic Kitchen BD',
        phone: '01912445566',
        email: 'farzana@organickitchen.bd',
        source: LeadSourceEnum.INSTAGRAM,
        stage: LeadStageEnum.CONTACTED,
        estimatedValue: 18500,
        leadScore: 70,
        notes: 'Instagram DM inquiry regarding custom branded packaging boxes and eco containers.',
        nextFollowUpAt: new Date(Date.now() + 36 * 3600 * 1000),
        followUpNote: 'Send packaging dimension specs',
        followUpStatus: 'PENDING',
        tags: ['Eco Package', 'F&B Sector'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Rafiqul Islam',
        companyName: 'Dhaka Tech Solutions',
        phone: '01912334455',
        email: 'rafiq@dhakatech.com',
        source: LeadSourceEnum.WEBSITE,
        stage: LeadStageEnum.QUALIFIED,
        estimatedValue: 95000,
        leadScore: 92,
        notes: 'Requirement verified: 60 premium executive gift hampers with custom laser logo engraving.',
        nextFollowUpAt: new Date(Date.now() + 4 * 3600 * 1000),
        followUpNote: 'Present final digital 3D mockup and pricing breakdown',
        followUpStatus: 'PENDING',
        tags: ['VIP', 'Corporate AGM', 'Ready to Buy'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Zubair Al-Mamun',
        companyName: 'CloudPoint Software',
        phone: '01799112233',
        email: 'zubair@cloudpoint.io',
        source: LeadSourceEnum.WHATSAPP,
        stage: LeadStageEnum.QUALIFIED,
        estimatedValue: 120000,
        leadScore: 90,
        notes: 'High intent deal for annual employee welcome kits (120 onboarding backpacks + bottles).',
        nextFollowUpAt: new Date(Date.now() + 8 * 3600 * 1000),
        followUpNote: 'Confirm sample approval with HR Director',
        followUpStatus: 'PENDING',
        tags: ['Tech Corporate', 'Recurring Client'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Mehnaz Chowdhury',
        companyName: 'Aura Spa & Wellness',
        phone: '01615556677',
        email: 'mehnaz@auraspa.bd',
        source: LeadSourceEnum.WEBSITE,
        stage: LeadStageEnum.PROPOSAL_SENT,
        estimatedValue: 38000,
        leadScore: 84,
        notes: 'Sent detailed proposal with tiered volume discount. Waiting for management sign-off.',
        nextFollowUpAt: new Date(Date.now() + 48 * 3600 * 1000),
        followUpNote: 'Follow up on proposal review status',
        followUpStatus: 'PENDING',
        tags: ['Hospitality', 'Custom Package'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Anisur Rahman',
        companyName: 'Delta Retail Hub',
        phone: '01822334455',
        email: 'anis@deltaretail.com.bd',
        source: LeadSourceEnum.STORE_INQUIRY,
        stage: LeadStageEnum.PROPOSAL_SENT,
        estimatedValue: 85000,
        leadScore: 88,
        notes: 'Store walk-in turned large bulk inquiry. Proposal delivered via email and WhatsApp.',
        nextFollowUpAt: new Date(Date.now() + 18 * 3600 * 1000),
        followUpNote: 'Call purchase manager to close deal',
        followUpStatus: 'PENDING',
        tags: ['Direct Store', 'High Priority'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Rezaul Karim',
        companyName: 'Karim Traders',
        phone: '01712998877',
        email: 'rezaul@karimtraders.com',
        source: LeadSourceEnum.STORE_INQUIRY,
        stage: LeadStageEnum.WON,
        estimatedValue: 150000,
        leadScore: 98,
        notes: 'Won and Converted! Order #ORD-9820 placed successfully with 50% advance bKash payment.',
        tags: ['Converted', 'Long Term Partner'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Sadia Afrin',
        companyName: 'Glow Beauty Studio',
        phone: '01688776655',
        email: 'sadia@glowbeauty.bd',
        source: LeadSourceEnum.INSTAGRAM,
        stage: LeadStageEnum.WON,
        estimatedValue: 42000,
        leadScore: 94,
        notes: 'Converted! Order #ORD-9844 fulfilled and delivered. Customer gave 5-star review.',
        tags: ['Converted', 'Satisfied Client'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Sultana Razia',
        companyName: 'Razia Textiles',
        phone: '01314445566',
        email: 'sultana@raziatraders.bd',
        source: LeadSourceEnum.PHONE_CALL,
        stage: LeadStageEnum.LOST,
        estimatedValue: 15000,
        leadScore: 40,
        lostReason: 'Competitor offered cheaper lower-grade alternate product',
        notes: 'Client prioritized lowest unit price over fabric longevity.',
        tags: ['Price Sensitive'],
        assignedStaffName: 'MD Belal Hossain',
      },
      {
        tenantId,
        storeId,
        name: 'Monir Hossain',
        companyName: 'Prime Decorators',
        phone: '01555667788',
        email: 'monir@primedecor.com',
        source: LeadSourceEnum.WHATSAPP,
        stage: LeadStageEnum.LOST,
        estimatedValue: 28000,
        leadScore: 45,
        lostReason: 'Needed delivery in 24 hours which was not feasible for custom printing',
        notes: 'Time constraint mismatch for specialized custom branding.',
        tags: ['Rush Order'],
        assignedStaffName: 'MD Belal Hossain',
      },
    ];

    const createdLeads: LeadEntity[] = [];
    for (const item of seedData) {
      // Check if lead with phone already exists for tenant
      const existing = await this.leadRepository.findOne({
        where: { tenantId, phone: item.phone },
      });
      if (!existing) {
        const lead = this.leadRepository.create(item);
        createdLeads.push(await this.leadRepository.save(lead));
      } else {
        createdLeads.push(existing);
      }
    }

    return createdLeads;
  }
}
