import {
  TransactionRecord,
  TransactionKpiItem,
  TransactionOverviewDonutItem,
  GatewayRevenueItem,
  TopMerchantRevenueItem,
} from './types';

export const TRANSACTIONS_KPIS: TransactionKpiItem[] = [
  {
    id: 'total-txns',
    title: 'Total Transactions',
    value: '8,456',
    trend: '18.6%',
    trendType: 'up',
    subtext: 'vs Jul 31 - Aug 6',
    iconType: 'total',
  },
  {
    id: 'total-amount',
    title: 'Total Amount',
    value: '৳18,42,450',
    trend: '14.3%',
    trendType: 'up',
    subtext: 'vs Jul 31 - Aug 6',
    iconType: 'amount',
  },
  {
    id: 'successful-txns',
    title: 'Successful',
    value: '7,892',
    trend: '93.3%',
    trendType: 'up',
    subtext: 'of all',
    iconType: 'success',
  },
  {
    id: 'refunded-txns',
    title: 'Refunded',
    value: '362',
    trend: '4.8%',
    trendType: 'down',
    subtext: 'vs Jul 31 - Aug 6',
    iconType: 'refund',
  },
  {
    id: 'failed-txns',
    title: 'Failed',
    value: '202',
    trend: '11.2%',
    trendType: 'down',
    subtext: 'vs Jul 31 - Aug 6',
    iconType: 'failed',
  },
];

export const INITIAL_TRANSACTIONS: TransactionRecord[] = [
  {
    id: 'TXN-2026-0008456',
    reference: 'REF: pay_1MTZsL2eZvKYlo2C',
    merchant: {
      name: 'Urban Style Store',
      domain: 'urbanstyle.easyco.com',
      email: 'rahim.hossain@email.com',
      storeId: 'store-urban-01',
    },
    customer: {
      name: 'Rahim Hossain',
      email: 'rahim.hossain@email.com',
    },
    type: 'Subscription Payment',
    gateway: 'stripe',
    gatewayDisplayName: 'Stripe',
    amount: '৳5,000.00',
    currencyLabel: 'BDT (Bangladeshi Taka)',
    secondaryAmount: 'USD 42.18',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 14, 2026',
      time: '10:32 AM',
    },
    description: 'Subscription payment for Growth Plan (Monthly)',
    metadata: 'Plan: Growth Plan (Monthly)',
    relatedOrder: 'ORD-2026-0005123',
    subscription: 'SUB-2026-000312',

    billingEmail: 'rahim.hossain@email.com',
    billingName: 'Rahim Hossain',
    cardHolder: 'Rahim Hossain',
    cardBrand: 'Visa',
    cardLast4: '4242',
    cardExpiry: '12 / 2028',
    country: 'Bangladesh',
    ipAddress: '103.86.XXX.XXX',
    device: 'Chrome on macOS',
    riskLevel: 'Low',

    gatewayTransactionId: 'pi_3M7tZtL2e2eXrY1o2C',
    paymentIntentId: 'pi_3M7tZtL2e2eXrY1o2C',
    chargeId: 'ch_3M7tZtL2e2eXrY1o2C',
    customerId: 'cus_M7tZtL2e2eXrY1o2C',
    capturedAt: 'Aug 14, 2026 10:31:27 AM',
    statementDescriptor: 'EASYCO*URBANSTYLE',
    responseCode: '200',
    avsCheck: 'Passed',
    threeDS: 'Not Required',
    mode: 'Live',

    planName: 'Growth Plan (Monthly)',
    planAmount: '৳5,000.00 / month',
    billingCycle: 'Monthly',
    nextBillingDate: 'Sep 14, 2026',
    tags: ['VIP Merchant', 'Auto-renew'],

    subtotal: '৳5,000.00',
    platformFee: '- ৳125.00',
    gatewayFee: '- ৳87.50',
    tax: '৳0.00',
    netAmountToPlatform: '৳4,787.50',
    fee: '৳125.00',
    netAmount: '৳4,875.00',
    paymentMethod: 'VISA Visa •••• 4242',

    timeline: [
      { id: '1', title: 'Payment Initiated', time: 'Aug 14, 2026 10:31:21 AM', completed: true },
      { id: '2', title: 'Payment Authorized', time: 'Aug 14, 2026 10:31:24 AM', completed: true },
      { id: '3', title: 'Payment Captured', time: 'Aug 14, 2026 10:31:27 AM', completed: true },
      { id: '4', title: 'Webhook Received', time: 'Aug 14, 2026 10:31:30 AM', completed: true },
      { id: '5', title: 'Marked as Success', time: 'Aug 14, 2026 10:31:32 AM', completed: true },
    ],

    webhooks: [
      {
        id: 'wh-1',
        event: 'charge.succeeded',
        status: 'Delivered',
        statusCode: 200,
        timestamp: 'Aug 14, 2026 10:31:30 AM',
        payloadPreview: '{"id": "evt_3M7tZtL2e", "type": "charge.succeeded", "amount": 500000}',
      },
      {
        id: 'wh-2',
        event: 'payment_intent.succeeded',
        status: 'Delivered',
        statusCode: 200,
        timestamp: 'Aug 14, 2026 10:31:28 AM',
        payloadPreview: '{"id": "evt_3M7tZtL2e_pi", "type": "payment_intent.succeeded"}',
      },
    ],

    refundsList: [
      {
        id: 'REF-2026-0012',
        amount: '৳0.00',
        reason: 'No refund requested for this active subscription.',
        date: 'N/A',
        status: 'Completed',
        refundedBy: 'System',
      },
    ],

    notesList: [
      {
        id: 'note-1',
        author: 'Platform Admin',
        role: 'Superadmin',
        text: 'Automatic monthly renewal succeeded on first attempt via Stripe customer token.',
        createdAt: 'Aug 14, 2026 10:32 AM',
      },
    ],
  },
  {
    id: 'TXN-2026-0008455',
    reference: 'REF: pay_1MTZrEL2eZvKYlo28',
    merchant: {
      name: 'ABC Fashion Store',
      domain: 'abcfashion.easyco.com',
      email: 'contact@abcfashion.com',
    },
    customer: {
      name: 'Tanvir Ahmed',
      email: 'contact@abcfashion.com',
    },
    type: 'Plan Upgrade',
    gateway: 'sslcommerz',
    gatewayDisplayName: 'SSLCommerz',
    amount: '৳2,500.00',
    currencyLabel: 'BDT (Bangladeshi Taka)',
    secondaryAmount: 'BDT',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 14, 2026',
      time: '09:17 AM',
    },
    description: 'Plan upgrade from Starter to Growth Tier',
    metadata: 'Upgrade: Growth Plan',
    relatedOrder: 'ORD-2026-0005120',
    subscription: 'SUB-2026-000305',
    billingEmail: 'contact@abcfashion.com',
    billingName: 'Tanvir Ahmed',
    cardHolder: 'Tanvir Ahmed',
    cardBrand: 'Mastercard',
    cardLast4: '8891',
    cardExpiry: '06 / 2027',
    country: 'Bangladesh',
    ipAddress: '103.112.XX.XX',
    device: 'Edge on Windows',
    riskLevel: 'Low',
    gatewayTransactionId: 'ssl_92817264510',
    paymentIntentId: 'ssl_intent_928172',
    chargeId: 'ssl_ch_928172',
    customerId: 'ssl_cus_11204',
    capturedAt: 'Aug 14, 2026 09:17:10 AM',
    statementDescriptor: 'EASYCO*ABCFA',
    responseCode: 'VALID',
    avsCheck: 'Passed',
    threeDS: 'Completed (OTP)',
    mode: 'Live',
    planName: 'Growth Plan',
    planAmount: '৳2,500.00 / month',
    billingCycle: 'Monthly',
    nextBillingDate: 'Sep 14, 2026',
    tags: ['Upgrade', 'SSLCommerz'],
    subtotal: '৳2,500.00',
    platformFee: '- ৳62.50',
    gatewayFee: '- ৳43.75',
    tax: '৳0.00',
    netAmountToPlatform: '৳2,393.75',
    fee: '৳62.50',
    netAmount: '৳2,437.50',
    paymentMethod: 'Mastercard •••• 8891',
    timeline: [
      { id: '1', title: 'Payment Initiated', time: 'Aug 14, 2026 09:16:40 AM', completed: true },
      { id: '2', title: 'OTP Verified', time: 'Aug 14, 2026 09:17:02 AM', completed: true },
      { id: '3', title: 'Payment Captured', time: 'Aug 14, 2026 09:17:10 AM', completed: true },
      { id: '4', title: 'Marked as Success', time: 'Aug 14, 2026 09:17:12 AM', completed: true },
    ],
  },
  {
    id: 'TXN-2026-0008454',
    reference: 'REF: trf_1MTZpuL2eZvKYlo2A',
    merchant: {
      name: 'Gadget Hub',
      domain: 'gadgethub.easyco.com',
      email: 'finance@gadgethub.com',
    },
    customer: {
      name: 'Gadget Hub Ltd.',
      email: 'finance@gadgethub.com',
    },
    type: 'Payout',
    gateway: 'bank_transfer',
    gatewayDisplayName: 'Bank Transfer',
    amount: '- ৳15,000.00',
    currencyLabel: 'BDT (Bangladeshi Taka)',
    secondaryAmount: 'BDT',
    isNegative: true,
    status: 'Success',
    createdAt: {
      date: 'Aug 13, 2026',
      time: '05:45 PM',
    },
    description: 'Weekly merchant payout settlement',
    metadata: 'Settlement Batch: BATCH-AUG-13',
    relatedOrder: 'PO-2026-091',
    subscription: 'SUB-2026-000280',
    billingEmail: 'finance@gadgethub.com',
    billingName: 'Gadget Hub Ltd.',
    cardHolder: 'City Bank Account',
    cardBrand: 'Bank',
    cardLast4: '9012',
    country: 'Bangladesh',
    ipAddress: '180.149.XX.XX',
    device: 'Automated BEFTN Batch',
    riskLevel: 'Low',
    gatewayTransactionId: 'beftn_9021847192',
    responseCode: '200 OK',
    mode: 'Live',
    planName: 'Enterprise Plan',
    planAmount: '৳15,000.00',
    billingCycle: 'Monthly',
    subtotal: '৳15,000.00',
    platformFee: '৳0.00',
    gatewayFee: '৳0.00',
    tax: '৳0.00',
    netAmountToPlatform: '- ৳15,000.00',
    fee: '৳0.00',
    netAmount: '- ৳15,000.00',
    paymentMethod: 'City Bank AC •••• 9012',
    timeline: [
      { id: '1', title: 'Payout Scheduled', time: 'Aug 13, 2026 05:00:00 PM', completed: true },
      { id: '2', title: 'BEFTN File Sent', time: 'Aug 13, 2026 05:30:00 PM', completed: true },
      { id: '3', title: 'Bank Acknowledged', time: 'Aug 13, 2026 05:45:00 PM', completed: true },
    ],
  },
  {
    id: 'TXN-2026-0008453',
    reference: 'REF: pay_1MTZoML2eZvKYlo29',
    merchant: {
      name: 'Book Haven',
      domain: 'bookhaven.easyco.com',
      email: 'orders@bookhaven.com',
    },
    customer: {
      name: 'Mahmudul Hasan',
      email: 'orders@bookhaven.com',
    },
    type: 'Subscription Payment',
    gateway: 'stripe',
    gatewayDisplayName: 'Stripe',
    amount: '৳2,500.00',
    secondaryAmount: 'USD 21.09',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 13, 2026',
      time: '04:21 PM',
    },
    description: 'Monthly Growth Plan fee',
    fee: '৳62.50',
    netAmount: '৳2,437.50',
    paymentMethod: 'Amex •••• 3005',
    subtotal: '৳2,500.00',
    platformFee: '- ৳62.50',
    gatewayFee: '- ৳43.75',
    tax: '৳0.00',
    netAmountToPlatform: '৳2,393.75',
  },
  {
    id: 'TXN-2026-0008452',
    reference: 'REF: pay_1MTZnML2eZvKYlo2B',
    merchant: {
      name: 'Daily Essentials',
      domain: 'dailyessentials.easyco.com',
      email: 'admin@dailyessentials.com',
    },
    customer: {
      name: 'Sultana Razia',
      email: 'admin@dailyessentials.com',
    },
    type: 'Subscription Payment',
    gateway: 'bkash',
    gatewayDisplayName: 'bKash',
    amount: '৳1,000.00',
    secondaryAmount: 'BDT',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 13, 2026',
      time: '02:11 PM',
    },
    fee: '৳15.00',
    netAmount: '৳985.00',
    paymentMethod: 'bKash Wallet 017••••332',
    subtotal: '৳1,000.00',
    platformFee: '- ৳25.00',
    gatewayFee: '- ৳15.00',
    tax: '৳0.00',
    netAmountToPlatform: '৳960.00',
  },
  {
    id: 'TXN-2026-0008451',
    reference: 'REF: ref_1MTZmL2eZvKYlo27',
    merchant: {
      name: 'Tech Solution',
      domain: 'techsolution.easyco.com',
      email: 'support@techsolution.com',
    },
    customer: {
      name: 'Saifur Rahman',
      email: 'support@techsolution.com',
    },
    type: 'Refund',
    gateway: 'stripe',
    gatewayDisplayName: 'Stripe',
    amount: '- ৳2,500.00',
    secondaryAmount: 'USD 21.09',
    isNegative: true,
    status: 'Refunded',
    createdAt: {
      date: 'Aug 13, 2026',
      time: '11:20 AM',
    },
    fee: '- ৳62.50',
    netAmount: '- ৳2,437.50',
    paymentMethod: 'Visa •••• 4242',
    subtotal: '- ৳2,500.00',
    platformFee: '৳62.50',
    gatewayFee: '৳43.75',
    tax: '৳0.00',
    netAmountToPlatform: '- ৳2,393.75',
  },
  {
    id: 'TXN-2026-0008450',
    reference: 'REF: pay_1MTZi9L2eZvKYlo26',
    merchant: {
      name: 'Home Mart',
      domain: 'homemart.easyco.com',
      email: 'billing@homemart.com',
    },
    customer: {
      name: 'Nayeem Sheikh',
      email: 'billing@homemart.com',
    },
    type: 'Subscription Payment',
    gateway: 'sslcommerz',
    gatewayDisplayName: 'SSLCommerz',
    amount: '৳2,500.00',
    secondaryAmount: 'BDT',
    isNegative: false,
    status: 'Failed',
    createdAt: {
      date: 'Aug 12, 2026',
      time: '08:33 PM',
    },
    fee: '৳0.00',
    netAmount: '৳0.00',
    paymentMethod: 'DBBL Nexus •••• 1044',
  },
  {
    id: 'TXN-2026-0008449',
    reference: 'REF: chg_1MTZrkL2eZvKYlo25',
    merchant: {
      name: 'FreshShop',
      domain: 'freshshop.easyco.com',
      email: 'hello@freshshop.com',
    },
    customer: {
      name: 'Farhana Akter',
      email: 'hello@freshshop.com',
    },
    type: 'One-time Charge',
    gateway: 'stripe',
    gatewayDisplayName: 'Stripe',
    amount: '৳750.00',
    secondaryAmount: 'USD 6.32',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 12, 2026',
      time: '07:12 PM',
    },
    fee: '৳18.75',
    netAmount: '৳731.25',
    paymentMethod: 'Visa •••• 1129',
  },
  {
    id: 'TXN-2026-0008448',
    reference: 'REF: pay_1MTZj2L2eZvKYlo24',
    merchant: {
      name: 'Beauty Palace',
      domain: 'beautypalace.easyco.com',
      email: 'care@beautypalace.com',
    },
    customer: {
      name: 'Nusrat Jahan',
      email: 'care@beautypalace.com',
    },
    type: 'Plan Upgrade',
    gateway: 'bkash',
    gatewayDisplayName: 'bKash',
    amount: '৳3,500.00',
    secondaryAmount: 'BDT',
    isNegative: false,
    status: 'Success',
    createdAt: {
      date: 'Aug 12, 2026',
      time: '04:50 PM',
    },
    fee: '৳52.50',
    netAmount: '৳3,447.50',
    paymentMethod: 'bKash Wallet 019••••998',
  },
  {
    id: 'TXN-2026-0008447',
    reference: 'REF: pay_1MTZIAL2eZvKYlo23',
    merchant: {
      name: 'Sports House',
      domain: 'sportshouse.easyco.com',
      email: 'sales@sportshouse.com',
    },
    customer: {
      name: 'Arifur Rahman',
      email: 'sales@sportshouse.com',
    },
    type: 'Subscription Payment',
    gateway: 'stripe',
    gatewayDisplayName: 'Stripe',
    amount: '৳2,500.00',
    secondaryAmount: 'USD 21.09',
    isNegative: false,
    status: 'Pending',
    createdAt: {
      date: 'Aug 12, 2026',
      time: '03:25 PM',
    },
    fee: '৳62.50',
    netAmount: '৳2,437.50',
    paymentMethod: 'Mastercard •••• 5510',
  },
];

export const TRANSACTION_DONUT_DATA: TransactionOverviewDonutItem[] = [
  { name: 'Successful', value: 7892, percentage: '93.3%', color: '#10B981' },
  { name: 'Refunded', value: 362, percentage: '4.3%', color: '#F59E0B' },
  { name: 'Failed', value: 202, percentage: '2.4%', color: '#EF4444' },
  { name: 'Pending', value: 0, percentage: '0%', color: '#94A3B8' },
];

export const GATEWAY_REVENUE_DATA: GatewayRevenueItem[] = [
  {
    id: 'gw-stripe',
    gateway: 'stripe',
    name: 'Stripe',
    amount: '৳12,45,000',
    percentage: 67.6,
    color: '#10B981',
  },
  {
    id: 'gw-ssl',
    gateway: 'sslcommerz',
    name: 'SSLCommerz',
    amount: '৳3,25,400',
    percentage: 17.6,
    color: '#10B981',
  },
  {
    id: 'gw-bkash',
    gateway: 'bkash',
    name: 'bKash',
    amount: '৳1,85,250',
    percentage: 10.0,
    color: '#10B981',
  },
  {
    id: 'gw-bank',
    gateway: 'bank_transfer',
    name: 'Bank Transfer',
    amount: '৳86,600',
    percentage: 4.7,
    color: '#10B981',
  },
];

export const TOP_MERCHANTS_REVENUE: TopMerchantRevenueItem[] = [
  {
    rank: 1,
    name: 'Urban Style Store',
    transactionCount: '2,120 transactions',
    amount: '৳2,45,000',
    badgeColor: 'bg-emerald-100 text-emerald-800',
  },
  {
    rank: 2,
    name: 'ABC Fashion Store',
    transactionCount: '1,624 transactions',
    amount: '৳1,80,000',
    badgeColor: 'bg-rose-100 text-rose-800',
  },
  {
    rank: 3,
    name: 'Gadget Hub',
    transactionCount: '1,152 transactions',
    amount: '৳1,45,000',
    badgeColor: 'bg-amber-100 text-amber-800',
  },
  {
    rank: 4,
    name: 'Book Haven',
    transactionCount: '1,048 transactions',
    amount: '৳1,28,000',
    badgeColor: 'bg-teal-100 text-teal-800',
  },
  {
    rank: 5,
    name: 'Daily Essentials',
    transactionCount: '842 transactions',
    amount: '৳98,000',
    badgeColor: 'bg-emerald-100 text-emerald-800',
  },
];
