import { MerchantKpiCardItem, MerchantRecord } from './types';

export const MERCHANT_KPIS: MerchantKpiCardItem[] = [
  {
    id: 'total-merchants',
    title: 'Total Merchants',
    value: '2,548',
    change: '12.5%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'users',
  },
  {
    id: 'active-merchants',
    title: 'Active Merchants',
    value: '2,214',
    change: '8.3%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'store',
  },
  {
    id: 'trial-merchants',
    title: 'Trial Merchants',
    value: '214',
    change: '12.2%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'hourglass',
  },
  {
    id: 'suspended-merchants',
    title: 'Suspended Merchants',
    value: '42',
    change: '3.4%',
    isPositive: false,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'pause',
  },
  {
    id: 'churned-merchants',
    title: 'Churned Merchants',
    value: '78',
    change: '7.6%',
    isPositive: false,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'user-minus',
  },
  {
    id: 'new-this-week',
    title: 'New This Week',
    value: '128',
    change: '18.7%',
    isPositive: true,
    period: 'vs Jul 31 - Aug 6',
    iconType: 'user-plus',
  },
];

export const INITIAL_MERCHANTS: MerchantRecord[] = [
  {
    id: 'm-1',
    name: 'Urban Style Store',
    domain: 'urbanstyle.easyco.com',
    initials: 'US',
    avatarBg: 'bg-emerald-600',
    contact: {
      email: 'rahim@email.com',
      phone: '+8801712345678',
    },
    stores: 3,
    plan: 'Business',
    status: 'Active',
    joinedAt: {
      date: 'Aug 14, 2026',
      time: '10:32 AM',
    },
    revenue30d: {
      amount: '৳2,45,000',
      trend: '22.5%',
      isPositive: true,
    },
    orders30d: {
      amount: '1,248',
      trend: '18.7%',
      isPositive: true,
    },
    mrr: '৳5,000',
    country: 'Bangladesh',
    registrationSource: 'Organic Search',
  },
  {
    id: 'm-2',
    name: 'ABC Fashion Store',
    domain: 'abcfashion.easyco.com',
    initials: 'AF',
    avatarBg: 'bg-rose-400',
    contact: {
      email: 'karim@email.com',
      phone: '+8801612345678',
    },
    stores: 2,
    plan: 'Growth',
    status: 'Active',
    joinedAt: {
      date: 'Aug 14, 2026',
      time: '09:17 AM',
    },
    revenue30d: {
      amount: '৳1,80,000',
      trend: '18.3%',
      isPositive: true,
    },
    orders30d: {
      amount: '982',
      trend: '15.2%',
      isPositive: true,
    },
    mrr: '৳2,500',
    country: 'Bangladesh',
    registrationSource: 'Facebook Ads',
  },
  {
    id: 'm-3',
    name: 'Gadget Hub',
    domain: 'gadgets.easyco.com',
    initials: 'GH',
    avatarBg: 'bg-indigo-400',
    contact: {
      email: 'mim@email.com',
      phone: '+8801523456789',
    },
    stores: 5,
    plan: 'Business',
    status: 'Active',
    joinedAt: {
      date: 'Aug 13, 2026',
      time: '08:50 PM',
    },
    revenue30d: {
      amount: '৳1,45,000',
      trend: '15.7%',
      isPositive: true,
    },
    orders30d: {
      amount: '752',
      trend: '12.1%',
      isPositive: true,
    },
    mrr: '৳5,000',
    country: 'Bangladesh',
    registrationSource: 'Direct',
  },
  {
    id: 'm-4',
    name: 'Book Haven',
    domain: 'bookhaven.easyco.com',
    initials: 'BH',
    avatarBg: 'bg-amber-500',
    contact: {
      email: 'sabbir@email.com',
      phone: '+8801812345678',
    },
    stores: 1,
    plan: 'Growth',
    status: 'Active',
    joinedAt: {
      date: 'Aug 13, 2026',
      time: '07:32 PM',
    },
    revenue30d: {
      amount: '৳1,28,000',
      trend: '12.1%',
      isPositive: true,
    },
    orders30d: {
      amount: '644',
      trend: '9.4%',
      isPositive: true,
    },
    mrr: '৳2,500',
    country: 'Bangladesh',
    registrationSource: 'Referral',
  },
  {
    id: 'm-5',
    name: 'Daily Essentials',
    domain: 'dailyessentials.easyco.com',
    initials: 'DE',
    avatarBg: 'bg-amber-400',
    contact: {
      email: 'sabir@email.com',
      phone: '+8801812345678',
    },
    stores: 2,
    plan: 'Starter',
    status: 'Active',
    joinedAt: {
      date: 'Aug 13, 2026',
      time: '06:12 PM',
    },
    revenue30d: {
      amount: '৳98,000',
      trend: '9.4%',
      isPositive: true,
    },
    orders30d: {
      amount: '512',
      trend: '7.3%',
      isPositive: true,
    },
    mrr: '৳1,000',
    country: 'Bangladesh',
    registrationSource: 'Google Ads',
  },
  {
    id: 'm-6',
    name: 'Tech Solution',
    domain: 'techsolution.easyco.com',
    initials: 'TS',
    avatarBg: 'bg-slate-400',
    contact: {
      email: 'nahid@email.com',
      phone: '+8801711122233',
    },
    stores: 1,
    plan: 'Starter',
    status: 'Trial',
    joinedAt: {
      date: 'Aug 13, 2026',
      time: '05:45 PM',
    },
    revenue30d: {
      amount: '৳12,500',
      trend: '5.4%',
      isPositive: true,
    },
    orders30d: {
      amount: '45',
      trend: '3.2%',
      isPositive: true,
    },
    mrr: '৳0',
    country: 'Bangladesh',
    registrationSource: 'Organic Search',
  },
  {
    id: 'm-7',
    name: 'Home Mart',
    domain: 'homemart.easyco.com',
    initials: 'HM',
    avatarBg: 'bg-teal-400',
    contact: {
      email: 'riyan@email.com',
      phone: '+8801912345678',
    },
    stores: 2,
    plan: 'Growth',
    status: 'Suspended',
    joinedAt: {
      date: 'Aug 12, 2026',
      time: '03:20 PM',
    },
    revenue30d: {
      amount: '৳0',
      trend: '-',
      isNeutral: true,
    },
    orders30d: {
      amount: '0',
      trend: '-',
      isNeutral: true,
    },
    mrr: '৳0',
    country: 'Bangladesh',
    registrationSource: 'Direct',
  },
  {
    id: 'm-8',
    name: 'FreshShop',
    domain: 'freshshop.easyco.com',
    initials: 'FS',
    avatarBg: 'bg-rose-500',
    contact: {
      email: 'tonu@email.com',
      phone: '+8801555555555',
    },
    stores: 1,
    plan: 'Starter',
    status: 'Churned',
    joinedAt: {
      date: 'Aug 10, 2026',
      time: '11:10 AM',
    },
    revenue30d: {
      amount: '৳0',
      trend: '-',
      isNeutral: true,
    },
    orders30d: {
      amount: '0',
      trend: '-',
      isNeutral: true,
    },
    mrr: '৳0',
    country: 'Bangladesh',
    registrationSource: 'Referral',
  },
];
