import { PermissionRecord, PermissionKpiMetric } from './types';

export const PERMISSIONS_KPIS: PermissionKpiMetric[] = [
  {
    id: 'kpi-total-perms',
    title: 'Total Permissions',
    value: '96',
    subtitle: 'All permissions in the system',
    type: 'total',
  },
  {
    id: 'kpi-system-perms',
    title: 'System Permissions',
    value: '72',
    subtitle: 'Default system permissions',
    type: 'system',
  },
  {
    id: 'kpi-custom-perms',
    title: 'Custom Permissions',
    value: '24',
    subtitle: 'Custom created permissions',
    type: 'custom',
  },
  {
    id: 'kpi-modules',
    title: 'Modules',
    value: '12',
    subtitle: 'Modules with permissions',
    type: 'modules',
  },
];

export const INITIAL_PERMISSIONS: PermissionRecord[] = [
  {
    id: 'perm-1',
    name: 'View Dashboard',
    description: 'Can view the main dashboard',
    permissionKey: 'dashboard.view',
    module: 'Dashboard',
    moduleIconName: 'LayoutDashboard',
    action: 'View',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 3,
    assignedUsersCount: 18,
    assignedGroupsCount: 2,
  },
  {
    id: 'perm-2',
    name: 'Manage Merchants',
    description: 'Can create, edit and manage merchants',
    permissionKey: 'merchants.manage',
    module: 'Merchants',
    moduleIconName: 'Users',
    action: 'Create / Edit',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 2,
    assignedUsersCount: 5,
    assignedGroupsCount: 1,
  },
  {
    id: 'perm-3',
    name: 'Delete Merchants',
    description: 'Can delete merchants',
    permissionKey: 'merchants.delete',
    module: 'Merchants',
    moduleIconName: 'Users',
    action: 'Delete',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 1,
    assignedUsersCount: 1,
    assignedGroupsCount: 1,
  },
  {
    id: 'perm-4',
    name: 'View Stores',
    description: 'Can view stores',
    permissionKey: 'stores.view',
    module: 'Stores',
    moduleIconName: 'Store',
    action: 'View',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 4,
    assignedUsersCount: 12,
    assignedGroupsCount: 2,
  },
  {
    id: 'perm-5',
    name: 'Manage Subscriptions',
    description: 'Can manage subscriptions',
    permissionKey: 'subscriptions.manage',
    module: 'Subscriptions',
    moduleIconName: 'CreditCard',
    action: 'Create / Edit',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 2,
    assignedUsersCount: 5,
    assignedGroupsCount: 1,
  },
  {
    id: 'perm-6',
    name: 'Cancel Subscriptions',
    description: 'Can cancel subscriptions',
    permissionKey: 'subscriptions.cancel',
    module: 'Subscriptions',
    moduleIconName: 'CreditCard',
    action: 'Update',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 2,
    assignedUsersCount: 5,
    assignedGroupsCount: 1,
  },
  {
    id: 'perm-7',
    name: 'View Plans',
    description: 'Can view plans',
    permissionKey: 'plans.view',
    module: 'Plans',
    moduleIconName: 'Layers',
    action: 'View',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 3,
    assignedUsersCount: 8,
    assignedGroupsCount: 2,
  },
  {
    id: 'perm-8',
    name: 'Manage Transactions',
    description: 'Can manage transactions',
    permissionKey: 'transactions.manage',
    module: 'Transactions',
    moduleIconName: 'ArrowLeftRight',
    action: 'Create / Edit',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 3,
    assignedUsersCount: 8,
    assignedGroupsCount: 2,
  },
  {
    id: 'perm-9',
    name: 'Refund Transactions',
    description: 'Can refund transactions',
    permissionKey: 'transactions.refund',
    module: 'Transactions',
    moduleIconName: 'ArrowLeftRight',
    action: 'Refund',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 2,
    assignedUsersCount: 4,
    assignedGroupsCount: 1,
  },
  {
    id: 'perm-10',
    name: 'View Reports',
    description: 'Can view reports',
    permissionKey: 'reports.view',
    module: 'Reports',
    moduleIconName: 'BarChart2',
    action: 'View',
    type: 'System',
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    updatedAtDate: 'May 14, 2026',
    updatedAtTime: '10:32 AM',
    assignedRolesCount: 5,
    assignedUsersCount: 15,
    assignedGroupsCount: 3,
  },
  // Additional permissions
  {
    id: 'perm-11',
    name: 'Manage Support Tickets',
    description: 'Can reply and assign support tickets',
    permissionKey: 'support.manage',
    module: 'Support',
    moduleIconName: 'Headphones',
    action: 'Create / Edit',
    type: 'Custom',
    status: 'Active',
    createdAtDate: 'Mar 01, 2024',
    createdAtTime: '11:00 AM',
    updatedAtDate: 'May 10, 2026',
    updatedAtTime: '02:15 PM',
    assignedRolesCount: 4,
    assignedUsersCount: 10,
    assignedGroupsCount: 2,
  },
  {
    id: 'perm-12',
    name: 'Export Platform Audits',
    description: 'Can export complete audit log trails',
    permissionKey: 'audits.export',
    module: 'Audit Logs',
    moduleIconName: 'FileText',
    action: 'Export',
    type: 'Custom',
    status: 'Active',
    createdAtDate: 'Apr 02, 2024',
    createdAtTime: '01:30 PM',
    updatedAtDate: 'May 08, 2026',
    updatedAtTime: '04:10 PM',
    assignedRolesCount: 1,
    assignedUsersCount: 1,
    assignedGroupsCount: 1,
  },
];
