import {
  RoleRecord,
  RoleKpiMetric,
  PermissionMatrixRow,
  PermissionSummarySlice,
  AccessRequestItem,
  PermissionGroupItem,
} from './types';

export const ROLES_KPIS: RoleKpiMetric[] = [
  {
    id: 'kpi-roles',
    title: 'Total Roles',
    value: '6',
    change: '+20%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'roles',
  },
  {
    id: 'kpi-permissions',
    title: 'Total Permissions',
    value: '96',
    change: '+8%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'permissions',
  },
  {
    id: 'kpi-users',
    title: 'Users with Access',
    value: '18',
    change: '+12%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'users',
  },
  {
    id: 'kpi-groups',
    title: 'Permission Groups',
    value: '8',
    change: '+14%',
    isPositive: true,
    periodText: 'vs last 30 days',
    type: 'groups',
  },
];

export const INITIAL_ROLES: RoleRecord[] = [
  {
    id: 'role-super-admin',
    name: 'Super Admin',
    type: 'System Role',
    description: 'Full access to all platform features, settings and data.',
    usersCount: 1,
    status: 'Active',
    createdAtDate: 'Jan 10, 2024',
    createdAtTime: '09:15 AM',
    lastUpdatedDate: 'May 14, 2026',
    lastUpdatedTime: '10:32 AM',
    isSystem: true,
  },
  {
    id: 'role-platform-manager',
    name: 'Platform Manager',
    type: 'System Role',
    description: 'Manage platform settings, merchants, plans, and operations.',
    usersCount: 4,
    status: 'Active',
    createdAtDate: 'Feb 02, 2024',
    createdAtTime: '11:20 AM',
    lastUpdatedDate: 'May 13, 2026',
    lastUpdatedTime: '04:20 PM',
    isSystem: true,
  },
  {
    id: 'role-support-agent',
    name: 'Support Agent',
    type: 'Custom Role',
    description: 'Access to support tickets and basic merchant information.',
    usersCount: 5,
    status: 'Active',
    createdAtDate: 'Mar 05, 2024',
    createdAtTime: '10:05 AM',
    lastUpdatedDate: 'May 12, 2026',
    lastUpdatedTime: '11:15 AM',
    isSystem: false,
  },
  {
    id: 'role-finance-admin',
    name: 'Finance Admin',
    type: 'Custom Role',
    description: 'Manage billing, transactions, payouts and financial reports.',
    usersCount: 3,
    status: 'Active',
    createdAtDate: 'Mar 20, 2024',
    createdAtTime: '01:40 PM',
    lastUpdatedDate: 'May 10, 2026',
    lastUpdatedTime: '09:10 AM',
    isSystem: false,
  },
  {
    id: 'role-content-manager',
    name: 'Content Manager',
    type: 'Custom Role',
    description: 'Manage platform content, emails, and notifications.',
    usersCount: 2,
    status: 'Active',
    createdAtDate: 'Apr 15, 2024',
    createdAtTime: '03:15 PM',
    lastUpdatedDate: 'May 09, 2026',
    lastUpdatedTime: '02:45 PM',
    isSystem: false,
  },
  {
    id: 'role-read-only-analyst',
    name: 'Read Only Analyst',
    type: 'Custom Role',
    description: 'Read-only access to analytics, reports and insights.',
    usersCount: 3,
    status: 'Active',
    createdAtDate: 'Apr 25, 2024',
    createdAtTime: '09:40 AM',
    lastUpdatedDate: 'May 08, 2026',
    lastUpdatedTime: '03:50 PM',
    isSystem: false,
  },
];

export const PERMISSION_MATRIX_ROWS: PermissionMatrixRow[] = [
  {
    id: 'mod-dashboard',
    module: 'Dashboard',
    iconName: 'LayoutDashboard',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'View Only',
    financeAdmin: 'Full Access',
    contentManager: 'Full Access',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-merchants',
    module: 'Merchants',
    iconName: 'Users',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'View Only',
    financeAdmin: 'No Permission',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-stores',
    module: 'Stores',
    iconName: 'Store',
    superAdmin: 'Full Access',
    platformManager: 'Create / Edit',
    supportAgent: 'View Only',
    financeAdmin: 'No Permission',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-subscriptions',
    module: 'Subscriptions',
    iconName: 'CreditCard',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'View Only',
    financeAdmin: 'No Permission',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-plans',
    module: 'Plans',
    iconName: 'Layers',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'No Permission',
    financeAdmin: 'No Permission',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-transactions',
    module: 'Transactions',
    iconName: 'ArrowLeftRight',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'View Only',
    financeAdmin: 'Create / Edit',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'View Only',
  },
  {
    id: 'mod-support',
    module: 'Support',
    iconName: 'Headphones',
    superAdmin: 'Full Access',
    platformManager: 'Full Access',
    supportAgent: 'Full Access',
    financeAdmin: 'Full Access',
    contentManager: 'No Permission',
    readOnlyAnalyst: 'No Permission',
  },
];

export const PERMISSIONS_SUMMARY_SLICES: PermissionSummarySlice[] = [
  {
    level: 'Full Access',
    count: 72,
    percentage: 75,
    color: '#059669', // Emerald
    hoverColor: '#047857',
  },
  {
    level: 'Create / Edit',
    count: 12,
    percentage: 12.5,
    color: '#F59E0B', // Amber
    hoverColor: '#D97706',
  },
  {
    level: 'View Only',
    count: 8,
    percentage: 8.3,
    color: '#3B82F6', // Blue
    hoverColor: '#2563EB',
  },
  {
    level: 'No Access',
    count: 4,
    percentage: 4.2,
    color: '#EF4444', // Red
    hoverColor: '#DC2626',
  },
];

export const ACCESS_REQUESTS_DATA: AccessRequestItem[] = [
  {
    id: 'req-1',
    userName: 'Sadia Ahmed',
    userEmail: 'sadia.ahmed@easyco.com',
    currentRole: 'Support Agent',
    requestedRole: 'Platform Manager',
    reason: 'Need access to merchant store configuration to resolve escalated tickets.',
    requestDate: 'Aug 14, 2026',
    status: 'Pending',
  },
  {
    id: 'req-2',
    userName: 'Tanvir Shuvo',
    userEmail: 'tanvir.shuvo@easyco.com',
    currentRole: 'Support Agent',
    requestedRole: 'Finance Admin',
    reason: 'Temporary audit support for billing dispute investigations.',
    requestDate: 'Aug 13, 2026',
    status: 'Pending',
  },
  {
    id: 'req-3',
    userName: 'Nahid Hasan',
    userEmail: 'nahid.hasan@easyco.com',
    currentRole: 'Platform Manager',
    requestedRole: 'Super Admin',
    reason: 'Infrastructure upgrade maintenance window access.',
    requestDate: 'Aug 12, 2026',
    status: 'Pending',
  },
];

export const PERMISSION_GROUPS_DATA: PermissionGroupItem[] = [
  {
    id: 'grp-1',
    name: 'Platform Operations',
    description: 'System configurations, domain routings, and cluster management.',
    permissionsCount: 24,
    assignedRolesCount: 2,
  },
  {
    id: 'grp-2',
    name: 'Merchant Management',
    description: 'Store onboarding, merchant KYC verification, and catalog control.',
    permissionsCount: 18,
    assignedRolesCount: 3,
  },
  {
    id: 'grp-3',
    name: 'Billing & Invoicing',
    description: 'Subscription pricing, transaction ledger, and payout disbursements.',
    permissionsCount: 16,
    assignedRolesCount: 2,
  },
  {
    id: 'grp-4',
    name: 'Support & Helpdesk',
    description: 'Ticket resolution, customer messaging, and internal notes.',
    permissionsCount: 12,
    assignedRolesCount: 4,
  },
  {
    id: 'grp-5',
    name: 'Security & Audits',
    description: '2FA policies, IP whitelists, and access log monitoring.',
    permissionsCount: 10,
    assignedRolesCount: 2,
  },
  {
    id: 'grp-6',
    name: 'Integrations & APIs',
    description: 'Webhook configurations, third-party apps, and payment gateways.',
    permissionsCount: 8,
    assignedRolesCount: 2,
  },
  {
    id: 'grp-7',
    name: 'Reports & Analytics',
    description: 'GMV calculations, revenue forecasting, and merchant growth charts.',
    permissionsCount: 5,
    assignedRolesCount: 5,
  },
  {
    id: 'grp-8',
    name: 'Marketing & Content',
    description: 'Email newsletter templates, push announcements, and blog pages.',
    permissionsCount: 3,
    assignedRolesCount: 3,
  },
];
