import { MigrationInterface, QueryRunner } from "typeorm";

export class AddStorePoliciesAndLimits1785955101190 implements MigrationInterface {
    name = 'AddStorePoliciesAndLimits1785955101190'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_categories_parentId"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_fromWarehouseId"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_toWarehouseId"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_productId"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_product_reviews_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_theme_purchases_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_theme_purchases_storeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stores_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stores_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stores_ownerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_staff_members_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_staff_members_storeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_staff_members_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_staff_members_inviteToken"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tranId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_orderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_storeSlug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_orderStatus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_customerPhone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orders_tenantId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abandoned_carts_customerPhone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abandoned_carts_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_orderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_trackingCode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_parentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_tenantId_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_categoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenantId_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_warehouseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_fromWarehouseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_toWarehouseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_newsletter_subscribers_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_newsletter_subscribers_storeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_newsletter_subscribers_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_email_campaigns_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_email_campaigns_storeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_reviews_isApproved"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_reviews_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_reviews_productId"`);
        await queryRunner.query(`CREATE TABLE "platform_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "configKey" character varying NOT NULL DEFAULT 'global', "heroContent" jsonb DEFAULT '{}', "pricingPlans" jsonb DEFAULT '[]', "testimonials" jsonb DEFAULT '[]', "faqs" jsonb DEFAULT '[]', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2c312e08f0edcdfbfb17c35067e" UNIQUE ("configKey"), CONSTRAINT "PK_8f9dc7b98d9e8fcb5eeb292bb95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "privacyPolicy" text`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "termsOfService" text`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "refundPolicy" text`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "blockedIps" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "blockedEmails" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "maxCodOrdersPerIp" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "stores" ADD "maxOrdersPerDay" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "staff_members" ALTER COLUMN "role" SET DEFAULT 'CUSTOM'`);
        await queryRunner.query(`CREATE INDEX "IDX_bc5e38342cac10295c5a9d4550" ON "abandoned_carts" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_65acd151236aaa0151aa420c92" ON "abandoned_carts" ("recoveryToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_7260711c6f06cde1157910aa62" ON "abandoned_carts" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dda1888315d072547f31dde8b8" ON "stock_transfers" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_22928dc6cdfdc43ef470de801f" ON "stock_transfers" ("toWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_684badd3999923339489222a0b" ON "stock_transfers" ("fromWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_35a3b1bdea06d49c59826fbddf" ON "stock_transfers" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ccb3b923ab454a614047f9442" ON "product_reviews" ("isApproved") `);
        await queryRunner.query(`CREATE INDEX "IDX_32edd80d91dff1bc19e79c8f16" ON "product_reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bc3d96c513181275abade8770" ON "product_reviews" ("tenantId") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_684badd3999923339489222a0b7" FOREIGN KEY ("fromWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_22928dc6cdfdc43ef470de801f4" FOREIGN KEY ("toWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_dda1888315d072547f31dde8b8b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_dda1888315d072547f31dde8b8b"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_22928dc6cdfdc43ef470de801f4"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_684badd3999923339489222a0b7"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bc3d96c513181275abade8770"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32edd80d91dff1bc19e79c8f16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ccb3b923ab454a614047f9442"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a3b1bdea06d49c59826fbddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_684badd3999923339489222a0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22928dc6cdfdc43ef470de801f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dda1888315d072547f31dde8b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7260711c6f06cde1157910aa62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65acd151236aaa0151aa420c92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc5e38342cac10295c5a9d4550"`);
        await queryRunner.query(`ALTER TABLE "staff_members" ALTER COLUMN "role" SET DEFAULT 'STORE_STAFF'`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "maxOrdersPerDay"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "maxCodOrdersPerIp"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "blockedEmails"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "blockedIps"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "refundPolicy"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "termsOfService"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP COLUMN "privacyPolicy"`);
        await queryRunner.query(`DROP TABLE "platform_configs"`);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_productId" ON "product_reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_tenantId" ON "product_reviews" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_isApproved" ON "product_reviews" ("isApproved") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_campaigns_storeId" ON "email_campaigns" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_campaigns_tenantId" ON "email_campaigns" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_newsletter_subscribers_email" ON "newsletter_subscribers" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_newsletter_subscribers_storeId" ON "newsletter_subscribers" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_newsletter_subscribers_tenantId" ON "newsletter_subscribers" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_productId" ON "stock_transfers" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_toWarehouseId" ON "stock_transfers" ("toWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_fromWarehouseId" ON "stock_transfers" ("fromWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_tenantId" ON "stock_transfers" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_productId" ON "inventory_stocks" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_warehouseId" ON "inventory_stocks" ("warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_tenantId" ON "inventory_stocks" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenantId_slug" ON "products" ("slug", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_categoryId" ON "products" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenantId" ON "products" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_tenantId_slug" ON "categories" ("slug", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_parentId" ON "categories" ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_tenantId" ON "categories" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_trackingCode" ON "consignments" ("trackingCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_orderId" ON "consignments" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenantId" ON "consignments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_abandoned_carts_tenantId" ON "abandoned_carts" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_abandoned_carts_customerPhone" ON "abandoned_carts" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_tenantId_createdAt" ON "orders" ("createdAt", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_customerPhone" ON "orders" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_orderStatus" ON "orders" ("orderStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_storeSlug" ON "orders" ("storeSlug") `);
        await queryRunner.query(`CREATE INDEX "IDX_orders_tenantId" ON "orders" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_orderId" ON "payments" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tranId" ON "payments" ("tranId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenantId" ON "payments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_staff_members_inviteToken" ON "staff_members" ("inviteToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_staff_members_email" ON "staff_members" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_staff_members_storeId" ON "staff_members" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_staff_members_tenantId" ON "staff_members" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stores_ownerId" ON "stores" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stores_slug" ON "stores" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_stores_tenantId" ON "stores" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_theme_purchases_storeId" ON "theme_purchases" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_theme_purchases_tenantId" ON "theme_purchases" ("tenantId") `);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_product_reviews_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_toWarehouseId" FOREIGN KEY ("toWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_fromWarehouseId" FOREIGN KEY ("fromWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_categories_parentId" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
