import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786996217133 implements MigrationInterface {
    name = 'InitialSchema1786996217133'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "refreshToken" text NOT NULL, "ipAddress" character varying(100), "userAgent" character varying(255), "isValid" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPER_ADMIN', 'STORE_OWNER', 'STORE_STAFF', 'CUSTOMER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "phone" character varying(50), "role" "public"."users_role_enum" NOT NULL DEFAULT 'CUSTOMER', "isActive" boolean NOT NULL DEFAULT true, "tenantId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "storefront_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "tenantId" uuid NOT NULL, "storeSlug" character varying(100) NOT NULL, "channel" character varying(50) NOT NULL DEFAULT 'direct', "utmSource" character varying(255), "utmMedium" character varying(255), "utmCampaign" character varying(255), "referrerHost" character varying(255), "landingPage" character varying(500), "pageViewCount" integer NOT NULL DEFAULT '1', "firstSeenAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastSeenAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7b923e9e7a49e8b470768171c6c" UNIQUE ("sessionId"), CONSTRAINT "PK_360e8605647a0e732c5d6a87203" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecbdea919b4d1434fe24302438" ON "storefront_sessions" ("tenantId", "firstSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3921079ff981d52f999a149422" ON "storefront_sessions" ("tenantId", "channel") `);
        await queryRunner.query(`CREATE TABLE "store_webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "targetUrl" character varying(500) NOT NULL, "events" jsonb NOT NULL DEFAULT '[]', "secret" character varying(128) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastTriggeredAt" TIMESTAMP WITH TIME ZONE, "failureCount" integer NOT NULL DEFAULT '0', "lastError" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_61cbc7e8ca9a24b5705ce6053cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a4649a70b12d79602a84d3b9ac" ON "store_webhooks" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TABLE "theme_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "themeId" character varying(100) NOT NULL, "tranId" character varying(100), "valId" character varying(100), "price" numeric(12,2) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'COMPLETED', "paymentMethod" character varying(50) NOT NULL DEFAULT 'BALANCE', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7d76573f75a55996815047a0315" UNIQUE ("tranId"), CONSTRAINT "PK_4e64d0692f4bf93d484a0622bb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stores_smsdriver_enum" AS ENUM('BULKSMSBD', 'GREENWEB', 'TWILIO', 'DISABLED')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_emaildriver_enum" AS ENUM('SMTP', 'SENDGRID', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(100) NOT NULL, "domain" character varying(255), "category" character varying(100), "phone" character varying(50), "address" text, "logo" text, "favicon" character varying(255), "metaTitle" character varying(255), "metaDescription" text, "facebookPixelId" character varying(255), "facebookCapiToken" text, "facebookTestEventCode" character varying(100), "tiktokPixelId" character varying(255), "googleTagManagerId" character varying(255), "googleAnalyticsId" character varying(255), "snapchatPixelId" character varying(255), "pinterestTagId" character varying(255), "activeThemeId" character varying(100) NOT NULL DEFAULT 'DEFAULT_MODERN', "unlockedThemeIds" jsonb NOT NULL DEFAULT '["DEFAULT_MODERN"]', "primaryColor" character varying(50) NOT NULL DEFAULT '#2563eb', "fontFamily" character varying(50) NOT NULL DEFAULT 'Inter', "heroBanners" jsonb DEFAULT '[]', "currency" character varying(10) NOT NULL DEFAULT 'BDT', "steadfastApiKey" character varying(255), "steadfastSecretKey" character varying(255), "pathaoClientId" character varying(255), "pathaoClientSecret" character varying(255), "smsDriver" "public"."stores_smsdriver_enum" NOT NULL DEFAULT 'BULKSMSBD', "smsApiKey" character varying(255), "smsSenderId" character varying(100), "emailDriver" "public"."stores_emaildriver_enum" NOT NULL DEFAULT 'SMTP', "smtpHost" character varying(255), "smtpPort" integer DEFAULT '587', "smtpUser" character varying(255), "smtpPass" character varying(255), "fromEmail" character varying(255), "ownerId" uuid NOT NULL, "tenantId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "privacyPolicy" text, "termsOfService" text, "refundPolicy" text, "blockedIps" jsonb DEFAULT '[]', "blockedEmails" jsonb DEFAULT '[]', "maxCodOrdersPerIp" integer DEFAULT '0', "maxOrdersPerDay" integer DEFAULT '0', "language" character varying(10) NOT NULL DEFAULT 'en', "timezone" character varying(64) NOT NULL DEFAULT 'Asia/Dhaka', "dateFormat" character varying(32) NOT NULL DEFAULT 'DD/MM/YYYY', "weightUnit" character varying(10) NOT NULL DEFAULT 'KG', "maintenanceMode" boolean NOT NULL DEFAULT false, "maintenanceMessage" text, "catalogModeEnabled" boolean NOT NULL DEFAULT false, "showOutOfStockProducts" boolean NOT NULL DEFAULT true, "orderNumberPrefix" character varying(20) NOT NULL DEFAULT 'ORD-', "autoConfirmOrders" boolean NOT NULL DEFAULT true, "invoiceFooterNote" text, "guestCheckoutEnabled" boolean NOT NULL DEFAULT true, "requireCustomerEmail" boolean NOT NULL DEFAULT false, "showCouponFieldAtCheckout" boolean NOT NULL DEFAULT true, "showOrderNoteFieldAtCheckout" boolean NOT NULL DEFAULT true, "minimumOrderAmount" integer DEFAULT '0', "allowCustomerRegistration" boolean NOT NULL DEFAULT true, "requireEmailVerification" boolean NOT NULL DEFAULT false, "allowCustomerReviews" boolean NOT NULL DEFAULT true, "autoApproveReviews" boolean NOT NULL DEFAULT true, "navigationLinks" jsonb DEFAULT '[]', "showHeroSection" boolean NOT NULL DEFAULT true, "showFeaturedProducts" boolean NOT NULL DEFAULT true, "showCategoriesSection" boolean NOT NULL DEFAULT true, "featuredProductsCount" integer NOT NULL DEFAULT '8', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_790b2968701a6ff5ff383237765" UNIQUE ("slug"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "name" character varying(120) NOT NULL, "areas" jsonb NOT NULL DEFAULT '[]', "deliveryCharge" numeric(12,2) NOT NULL DEFAULT '60', "estimatedDeliveryTime" character varying(60), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_88bc4c12be62436a61930cf34a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51308fdbb7eebcfecb2973b7b7" ON "delivery_zones" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TABLE "store_api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "name" character varying(120) NOT NULL, "keyPrefix" character varying(24) NOT NULL, "keyHash" character varying(128) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b692e3571a51e2851da35632e95" UNIQUE ("keyHash"), CONSTRAINT "PK_c62d313076908031969178123e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_326778db9810dec33ed988b0b9" ON "store_api_keys" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TABLE "staff_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "userId" uuid, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(50), "role" character varying(100) NOT NULL DEFAULT 'CUSTOM', "permissions" jsonb NOT NULL DEFAULT '[]', "status" character varying(50) NOT NULL DEFAULT 'PENDING_INVITE', "inviteToken" character varying(255), "inviteExpiresAt" TIMESTAMP WITH TIME ZONE, "invitedByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cdad75efe024402db5d51140960" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sms_logs_status_enum" AS ENUM('SENT', 'FAILED', 'SANDBOX')`);
        await queryRunner.query(`CREATE TABLE "sms_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientPhone" character varying(50) NOT NULL, "message" text NOT NULL, "gateway" character varying(50) NOT NULL DEFAULT 'BULKSMSBD', "status" "public"."sms_logs_status_enum" NOT NULL DEFAULT 'SANDBOX', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_811e3a63f5e14a50475c6e8be3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."push_notifications_type_enum" AS ENUM('ORDER_PLACED', 'ORDER_STATUS_CHANGED', 'STOCK_LOW', 'PAYMENT_RECEIVED')`);
        await queryRunner.query(`CREATE TABLE "push_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."push_notifications_type_enum" NOT NULL DEFAULT 'ORDER_PLACED', "isRead" boolean NOT NULL DEFAULT false, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99bba16844a5a39fd0d23fb8835" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_gateway_enum" AS ENUM('SSLCOMMERZ', 'BKASH', 'NAGAD', 'STRIPE', 'PAYPAL', 'COD', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum" AS ENUM('BKASH', 'NAGAD', 'ROCKET', 'UPAY', 'CARD', 'BANK_TRANSFER', 'COD')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "orderNumber" character varying(50) NOT NULL, "customerId" uuid, "transactionNumber" character varying(50), "tranId" character varying(100) NOT NULL, "valId" character varying(100), "amount" numeric(12,2) NOT NULL, "refundedAmount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'BDT', "gateway" "public"."payments_gateway_enum" NOT NULL DEFAULT 'SSLCOMMERZ', "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL DEFAULT 'CARD', "cardType" character varying(100), "bankTranId" character varying(100), "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "failureReason" text, "paidAt" TIMESTAMP WITH TIME ZONE, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f0d96c36191806c4067604b6391" UNIQUE ("tranId"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_customer" ON "payments" ("tenantId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_order" ON "payments" ("tenantId", "orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_method" ON "payments" ("tenantId", "paymentMethod") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_gateway" ON "payments" ("tenantId", "gateway") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_status" ON "payments" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_created" ON "payments" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."refunds_status_enum" AS ENUM('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "refundNumber" character varying(50) NOT NULL, "orderId" uuid NOT NULL, "paymentId" uuid NOT NULL, "returnId" uuid, "amount" numeric(12,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'BDT', "method" character varying(100) NOT NULL, "status" "public"."refunds_status_enum" NOT NULL DEFAULT 'REQUESTED', "gatewayRefundId" character varying(100), "reason" text, "failureReason" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completedAt" TIMESTAMP WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_524c82c2d96896d64c38a00554e" UNIQUE ("refundNumber"), CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_gateways_code_enum" AS ENUM('SSLCOMMERZ', 'BKASH', 'NAGAD', 'STRIPE', 'PAYPAL', 'COD', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_gateways_status_enum" AS ENUM('CONNECTED', 'DISCONNECTED', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "payment_gateways" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" "public"."payment_gateways_code_enum" NOT NULL, "name" character varying(100) NOT NULL, "kind" character varying(50) NOT NULL, "status" "public"."payment_gateways_status_enum" NOT NULL DEFAULT 'DISCONNECTED', "isEnabled" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2b022a3aafb792a1afe3e14e06f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_payment_gateways_tenant_code" ON "payment_gateways" ("tenantId", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_events_type_enum" AS ENUM('PAYMENT_INITIATED', 'GATEWAY_PROCESSING', 'WEBHOOK_RECEIVED', 'PAYMENT_VERIFIED', 'PAYMENT_SUCCEEDED', 'PAYMENT_FAILED', 'PAYMENT_CANCELLED', 'ORDER_UPDATED', 'REFUND_INITIATED', 'REFUND_COMPLETED', 'REFUND_FAILED')`);
        await queryRunner.query(`CREATE TABLE "payment_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentId" uuid NOT NULL, "type" "public"."payment_events_type_enum" NOT NULL, "message" text, "externalEventId" character varying(190), "metadata" jsonb, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9f1d16fc78b33e676940a32e8b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payment_events_tenant_payment" ON "payment_events" ("tenantId", "paymentId") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "productTitle" character varying(255) NOT NULL, "variantId" uuid, "variantTitle" character varying(255), "sku" character varying(100), "unitPrice" numeric(12,2) NOT NULL, "quantity" integer NOT NULL, "totalPrice" numeric(12,2) NOT NULL, "orderId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentmethod_enum" AS ENUM('COD', 'BKASH', 'NAGAD', 'SSLCOMMERZ')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentstatus_enum" AS ENUM('UNPAID', 'PAID', 'REFUNDED', 'COD_PENDING', 'COD_COLLECTED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderNumber" character varying(50) NOT NULL, "customerId" uuid, "customerName" character varying(255) NOT NULL, "customerPhone" character varying(50) NOT NULL, "customerEmail" character varying(255), "shippingAddress" text NOT NULL, "area" character varying(100), "thana" character varying(100), "district" character varying(100), "division" character varying(100), "city" character varying(100) NOT NULL DEFAULT 'Dhaka', "customerNote" text, "internalNote" text, "deliveryFee" numeric(12,2) NOT NULL DEFAULT '60', "subtotal" numeric(12,2) NOT NULL, "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "couponCode" character varying(50), "grandTotal" numeric(12,2) NOT NULL, "paymentMethod" "public"."orders_paymentmethod_enum" NOT NULL DEFAULT 'COD', "paymentStatus" "public"."orders_paymentstatus_enum" NOT NULL DEFAULT 'UNPAID', "orderStatus" character varying(50) NOT NULL DEFAULT 'PENDING', "storeSlug" character varying(100) NOT NULL, "channel" character varying(50) NOT NULL DEFAULT 'direct', "utmSource" character varying(255), "utmMedium" character varying(255), "utmCampaign" character varying(255), "referrerHost" character varying(255), "sessionId" uuid, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."return_items_condition_enum" AS ENUM('GOOD', 'DAMAGED', 'USED', 'DEFECTIVE', 'WRONG_ITEM')`);
        await queryRunner.query(`CREATE TABLE "return_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "returnId" uuid NOT NULL, "orderItemId" uuid NOT NULL, "quantity" integer NOT NULL, "reason" text, "condition" "public"."return_items_condition_enum", "restockDecision" boolean, "inspectionNote" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6e6c1db00d31ab59c1bc22f6cb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."returns_status_enum" AS ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'PICKUP_PENDING', 'IN_TRANSIT', 'RECEIVED', 'INSPECTED', 'ACCEPTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "returns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "returnNumber" character varying(50) NOT NULL, "orderId" uuid NOT NULL, "status" "public"."returns_status_enum" NOT NULL DEFAULT 'REQUESTED', "reason" text, "note" text, "rejectionReason" text, "tenantId" uuid NOT NULL, "requestedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "approvedAt" TIMESTAMP WITH TIME ZONE, "receivedAt" TIMESTAMP WITH TIME ZONE, "inspectedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_424cbc15e555622e94842e9a303" UNIQUE ("returnNumber"), CONSTRAINT "PK_27a2f1895a71519ebfec7850361" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_previousstatus_enum" AS ENUM('PENDING', 'ON_HOLD', 'CONFIRMED', 'PROCESSING', 'READY_TO_SHIP', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURNED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_newstatus_enum" AS ENUM('PENDING', 'ON_HOLD', 'CONFIRMED', 'PROCESSING', 'READY_TO_SHIP', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURNED')`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "previousStatus" "public"."order_status_history_previousstatus_enum", "newStatus" "public"."order_status_history_newstatus_enum" NOT NULL, "changedBy" character varying(255) NOT NULL, "reason" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "content" text NOT NULL, "isCustomerVisible" boolean NOT NULL DEFAULT false, "createdBy" character varying(255) NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_98b207341585da2a0faa9b841ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "abandoned_carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerName" character varying(255), "customerPhone" character varying(50) NOT NULL, "customerEmail" character varying(255), "shippingAddress" text, "itemsJson" jsonb NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "recoveryToken" character varying(100) NOT NULL, "isRecovered" boolean NOT NULL DEFAULT false, "lastRemindedAt" TIMESTAMP WITH TIME ZONE, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_65acd151236aaa0151aa420c92c" UNIQUE ("recoveryToken"), CONSTRAINT "PK_cc75c0c4948585c6630578c4739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc5e38342cac10295c5a9d4550" ON "abandoned_carts" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_65acd151236aaa0151aa420c92" ON "abandoned_carts" ("recoveryToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_7260711c6f06cde1157910aa62" ON "abandoned_carts" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."marketing_pixels_provider_enum" AS ENUM('META', 'GOOGLE_ANALYTICS', 'GOOGLE_ADS', 'TIKTOK')`);
        await queryRunner.query(`CREATE TYPE "public"."marketing_pixels_status_enum" AS ENUM('CONNECTED', 'DISCONNECTED')`);
        await queryRunner.query(`CREATE TABLE "marketing_pixels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "provider" "public"."marketing_pixels_provider_enum" NOT NULL, "pixelId" character varying(255) NOT NULL, "accessToken" text, "status" "public"."marketing_pixels_status_enum" NOT NULL DEFAULT 'CONNECTED', "lastEventAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f80100c24df82c91a5d3ebba11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_617b8a1ad8c7022d950ebb4b90" ON "marketing_pixels" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a6314615c24e8933a35207123" ON "marketing_pixels" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a742ccfc2a97502f2721698b7" ON "marketing_pixels" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TYPE "public"."marketing_event_logs_status_enum" AS ENUM('SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "marketing_event_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "eventName" character varying(100) NOT NULL, "source" character varying(100) NOT NULL, "orderRef" character varying(100), "status" "public"."marketing_event_logs_status_enum" NOT NULL, "errorDetails" text, "payloadJson" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bcb48fb1b09172be6090b69be8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6b0b0c4b5a362b641155da175" ON "marketing_event_logs" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb6f880375d6be6cf4e4871dd3" ON "marketing_event_logs" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff909d6e41a974d0a020e30733" ON "marketing_event_logs" ("tenantId", "storeId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dff5896f08f92a78af04eba720" ON "marketing_event_logs" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TYPE "public"."marketing_event_configs_eventname_enum" AS ENUM('PageView', 'ViewContent', 'AddToCart', 'InitiateCheckout', 'Purchase')`);
        await queryRunner.query(`CREATE TABLE "marketing_event_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "eventName" "public"."marketing_event_configs_eventname_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8f22aa1cacb3780300ae77e599" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68514ad668da8bf80ddbb1e2c1" ON "marketing_event_configs" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca679bce44a6852cf7538084f2" ON "marketing_event_configs" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e97e38e81aed2eff897173b91" ON "marketing_event_configs" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TABLE "consignment_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "consignmentId" uuid NOT NULL, "status" character varying(50) NOT NULL, "eventTimestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "location" character varying(255), "description" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fce5afac235566444213ee91834" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."consignments_courierprovider_enum" AS ENUM('STEADFAST', 'PATHAO', 'PAPERFLY', 'REDX')`);
        await queryRunner.query(`CREATE TYPE "public"."consignments_codstatus_enum" AS ENUM('NOT_APPLICABLE', 'PENDING', 'COLLECTED', 'SETTLED', 'RETURNED')`);
        await queryRunner.query(`CREATE TYPE "public"."consignments_status_enum" AS ENUM('PENDING', 'BOOKED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING', 'RETURNED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "consignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipmentNumber" character varying(50) NOT NULL, "trackingCode" character varying(100), "orderId" uuid NOT NULL, "orderNumber" character varying(50) NOT NULL, "customerId" uuid, "courierProvider" "public"."consignments_courierprovider_enum" NOT NULL DEFAULT 'STEADFAST', "recipientName" character varying(255) NOT NULL, "recipientPhone" character varying(50) NOT NULL, "recipientAddress" text NOT NULL, "city" character varying(100) NOT NULL DEFAULT 'Dhaka', "pickupAddress" text, "codAmount" numeric(12,2) NOT NULL, "codStatus" "public"."consignments_codstatus_enum" NOT NULL DEFAULT 'PENDING', "codCollectedAt" TIMESTAMP WITH TIME ZONE, "codSettledAt" TIMESTAMP WITH TIME ZONE, "deliveryCharge" numeric(12,2) NOT NULL DEFAULT '60', "parcelWeight" numeric(8,3) NOT NULL DEFAULT '0.5', "parcelType" character varying(50) NOT NULL DEFAULT 'PARCEL', "parcelDimensions" character varying(100), "deliveryNote" text, "specialInstructions" text, "status" "public"."consignments_status_enum" NOT NULL DEFAULT 'PENDING', "idempotencyKey" character varying(100), "tenantId" uuid NOT NULL, "lastSyncAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ac4a3e322938f3ea03ee389f7c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tracking_code" ON "consignments" ("trackingCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_customer" ON "consignments" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenant_order" ON "consignments" ("tenantId", "orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenant_courier" ON "consignments" ("tenantId", "courierProvider") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenant_cod_status" ON "consignments" ("tenantId", "codStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenant_status" ON "consignments" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_consignments_tenant_created" ON "consignments" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."courier_integrations_provider_enum" AS ENUM('STEADFAST', 'PATHAO', 'PAPERFLY', 'REDX')`);
        await queryRunner.query(`CREATE TABLE "courier_integrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "provider" "public"."courier_integrations_provider_enum" NOT NULL, "isEnabled" boolean NOT NULL DEFAULT false, "isDefault" boolean NOT NULL DEFAULT false, "encryptedCredentials" text, "sandbox" boolean NOT NULL DEFAULT false, "autoCreateShipment" boolean NOT NULL DEFAULT false, "autoUpdateTracking" boolean NOT NULL DEFAULT true, "lastApiSyncAt" TIMESTAMP WITH TIME ZONE, "lastWebhookAt" TIMESTAMP WITH TIME ZONE, "apiCallsTotal" integer NOT NULL DEFAULT '0', "apiCallsFailed" integer NOT NULL DEFAULT '0', "lastTestedAt" TIMESTAMP WITH TIME ZONE, "lastTestSucceeded" boolean, "lastTestMessage" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_courier_integrations_tenant_provider" UNIQUE ("tenantId", "provider"), CONSTRAINT "PK_8f205372d9fb8fd1d5ea5997232" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_courier_integrations_tenant" ON "courier_integrations" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."categories_status_enum" AS ENUM('ACTIVE', 'DRAFT', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "status" "public"."categories_status_enum" NOT NULL DEFAULT 'ACTIVE', "sortOrder" integer NOT NULL DEFAULT '0', "parentId" uuid, "icon" character varying(255), "image" text, "isFeatured" boolean NOT NULL DEFAULT false, "seoTitle" character varying(255), "metaDescription" text, "isVisible" boolean NOT NULL DEFAULT true, "showInStorefront" boolean NOT NULL DEFAULT true, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be815db99f0960c3f22d13de34" ON "categories" ("tenantId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0d5731e7002ff4e4b04590a7f" ON "categories" ("tenantId", "parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4492aaaf3bac186ce7ce379a45" ON "categories" ("tenantId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8191c898401ab93cb04ce1986" ON "categories" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "logoUrl" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_brands_tenant_slug" ON "brands" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE TABLE "collections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_21c00b1ebbd41ba1354242c5c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_collections_tenant_slug" ON "collections" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" text NOT NULL, "altText" character varying(255), "isPrimary" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "productId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_product_images_product_tenant" ON "product_images" ("productId", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL DEFAULT '', "sku" character varying(100), "barcode" character varying(100), "price" numeric(12,2), "compareAtPrice" numeric(12,2), "costPrice" numeric(12,2), "imageId" uuid, "isEnabled" boolean NOT NULL DEFAULT true, "combinationKey" character varying(255), "options" jsonb NOT NULL DEFAULT '[]', "attributes" jsonb, "productId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_variants_prod_comb" ON "product_variants" ("productId", "combinationKey") WHERE "combinationKey" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_variants_tenant_sku" ON "product_variants" ("tenantId", "sku") WHERE "sku" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_product_variants_tenant_id" ON "product_variants" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_variants_prod_id" ON "product_variants" ("productId") `);
        await queryRunner.query(`CREATE TABLE "attribute_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying(255) NOT NULL, "value" character varying(255) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "attributeId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_696cd598705915238f202da10a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_attribute_options_attr" ON "attribute_options" ("attributeId") `);
        await queryRunner.query(`CREATE TYPE "public"."attribute_definitions_type_enum" AS ENUM('TEXT', 'NUMBER', 'BOOLEAN', 'SELECT', 'MULTI_SELECT', 'DATE', 'URL')`);
        await queryRunner.query(`CREATE TABLE "attribute_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "key" character varying(255) NOT NULL, "type" "public"."attribute_definitions_type_enum" NOT NULL DEFAULT 'TEXT', "description" text, "isRequired" boolean NOT NULL DEFAULT false, "isFilterable" boolean NOT NULL DEFAULT true, "isVariantOption" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0430dd4f09c3ff09daa16484676" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_attribute_definitions_tenant_slug" ON "attribute_definitions" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_attribute_definitions_tenant_key" ON "attribute_definitions" ("tenantId", "key") `);
        await queryRunner.query(`CREATE TABLE "product_attribute_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "attributeId" uuid NOT NULL, "value" text NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b124baf1272037deac1c21cffe1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_product_attr_values_tenant" ON "product_attribute_values" ("tenantId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_attr_values_prod_attr" ON "product_attribute_values" ("productId", "attributeId") `);
        await queryRunner.query(`CREATE TABLE "shipping_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "isDefault" boolean NOT NULL DEFAULT false, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ff6dbc0cbb1403e01f92a6ee3a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_shipping_profiles_tenant" ON "shipping_profiles" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."products_producttype_enum" AS ENUM('PHYSICAL', 'DIGITAL', 'SERVICE')`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."products_taxcategory_enum" AS ENUM('STANDARD_VAT', 'REDUCED', 'ZERO_RATED', 'EXEMPT')`);
        await queryRunner.query(`CREATE TYPE "public"."products_discounttype_enum" AS ENUM('NONE', 'PERCENTAGE', 'FIXED')`);
        await queryRunner.query(`CREATE TYPE "public"."products_weightunit_enum" AS ENUM('KG', 'G', 'LB', 'OZ')`);
        await queryRunner.query(`CREATE TYPE "public"."products_dimensionunit_enum" AS ENUM('CM', 'M', 'IN')`);
        await queryRunner.query(`CREATE TYPE "public"."products_digitaldeliverytype_enum" AS ENUM('DOWNLOAD', 'ACCESS_LINK', 'LICENSE_KEY', 'EXTERNAL')`);
        await queryRunner.query(`CREATE TYPE "public"."products_servicedeliverytype_enum" AS ENUM('ONLINE', 'ONSITE', 'LOCATION')`);
        await queryRunner.query(`CREATE TYPE "public"."products_servicedurationunit_enum" AS ENUM('MINUTES', 'HOURS', 'DAYS')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "productType" "public"."products_producttype_enum" NOT NULL DEFAULT 'PHYSICAL', "status" "public"."products_status_enum" NOT NULL DEFAULT 'DRAFT', "sku" character varying(100), "barcode" character varying(100), "trackInventory" boolean NOT NULL DEFAULT true, "allowBackorder" boolean NOT NULL DEFAULT false, "lowStockThreshold" integer NOT NULL DEFAULT '10', "hasVariants" boolean NOT NULL DEFAULT false, "basePrice" numeric(12,2) NOT NULL DEFAULT '0', "compareAtPrice" numeric(12,2), "costPrice" numeric(12,2), "taxRate" numeric(5,2) NOT NULL DEFAULT '0', "isTaxInclusive" boolean NOT NULL DEFAULT false, "taxCategory" "public"."products_taxcategory_enum" NOT NULL DEFAULT 'STANDARD_VAT', "discountType" "public"."products_discounttype_enum" NOT NULL DEFAULT 'NONE', "discountValue" numeric(12,2) NOT NULL DEFAULT '0', "discountStartsAt" TIMESTAMP WITH TIME ZONE, "discountEndsAt" TIMESTAMP WITH TIME ZONE, "isPublished" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP WITH TIME ZONE, "shippingRequired" boolean NOT NULL DEFAULT true, "weight" numeric(10,3), "weightUnit" "public"."products_weightunit_enum" NOT NULL DEFAULT 'KG', "length" numeric(10,2), "width" numeric(10,2), "height" numeric(10,2), "dimensionUnit" "public"."products_dimensionunit_enum" NOT NULL DEFAULT 'CM', "shippingProfileId" uuid, "isFragile" boolean NOT NULL DEFAULT false, "digitalDeliveryType" "public"."products_digitaldeliverytype_enum", "digitalAssetUrl" character varying(500), "downloadLimit" integer, "downloadExpiryDays" integer, "serviceDeliveryType" "public"."products_servicedeliverytype_enum", "serviceDuration" numeric(8,2), "serviceDurationUnit" "public"."products_servicedurationunit_enum", "seoTitle" character varying(255), "metaDescription" text, "canonicalUrl" character varying(500), "isSearchEngineIndexed" boolean NOT NULL DEFAULT true, "categoryId" uuid, "brandId" uuid, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenant_brand" ON "products" ("tenantId", "brandId") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenant_category" ON "products" ("tenantId", "categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenant_type" ON "products" ("tenantId", "productType") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_tenant_status" ON "products" ("tenantId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_products_tenant_slug" ON "products" ("tenantId", "slug") `);
        await queryRunner.query(`CREATE TABLE "inventory_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "variantId" uuid, "warehouseId" uuid NOT NULL, "quantityOnHand" integer NOT NULL DEFAULT '0', "quantityReserved" integer NOT NULL DEFAULT '0', "reorderPoint" integer NOT NULL DEFAULT '5', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_092904cbd29becfe86bac755225" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_tenant_var" ON "inventory_stocks" ("tenantId", "variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_tenant_wh" ON "inventory_stocks" ("tenantId", "warehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_stocks_tenant_prod" ON "inventory_stocks" ("tenantId", "productId") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(100) NOT NULL, "isDefault" boolean NOT NULL DEFAULT false, "address" text, "phone" character varying(50), "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fromWarehouseId" uuid NOT NULL, "toWarehouseId" uuid NOT NULL, "productId" uuid NOT NULL, "quantity" integer NOT NULL, "notes" text, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dda1888315d072547f31dde8b8" ON "stock_transfers" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_22928dc6cdfdc43ef470de801f" ON "stock_transfers" ("toWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_684badd3999923339489222a0b" ON "stock_transfers" ("fromWarehouseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_35a3b1bdea06d49c59826fbddf" ON "stock_transfers" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_type_enum" AS ENUM('IN', 'OUT', 'ADJUSTMENT', 'INITIAL_STOCK', 'RESERVED', 'RELEASED', 'RETURNED', 'TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "variantId" uuid, "inventoryStockId" uuid, "type" "public"."inventory_movements_type_enum" NOT NULL DEFAULT 'ADJUSTMENT', "quantity" integer NOT NULL, "previousQuantity" integer NOT NULL, "newQuantity" integer NOT NULL, "reason" character varying(255) NOT NULL DEFAULT 'Manual Adjustment', "note" text, "referenceType" character varying(100), "referenceId" character varying(100), "createdBy" character varying(255), "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_movements_stock" ON "inventory_movements" ("inventoryStockId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_movements_var" ON "inventory_movements" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_movements_tenant" ON "inventory_movements" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_movements_prod" ON "inventory_movements" ("productId") `);
        await queryRunner.query(`CREATE TABLE "newsletter_subscribers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "email" character varying(255) NOT NULL, "name" character varying(255), "isSubscribed" boolean NOT NULL DEFAULT true, "source" character varying(100) NOT NULL DEFAULT 'STOREFRONT_FOOTER', "subscribedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "unsubscribedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_38f9333e9961b2fdb589128d19b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "title" character varying(255) NOT NULL, "subject" character varying(255) NOT NULL, "contentHtml" text NOT NULL, "recipientType" character varying(100) NOT NULL DEFAULT 'ALL_SUBSCRIBERS', "totalSent" integer NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'DRAFT', "sentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_72bad329795785308e66d562350" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_source_enum" AS ENUM('ONLINE_STORE', 'MANUAL', 'POS', 'IMPORT')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(255), "phone" character varying(50) NOT NULL, "status" "public"."customers_status_enum" NOT NULL DEFAULT 'ACTIVE', "source" "public"."customers_source_enum" NOT NULL DEFAULT 'ONLINE_STORE', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37c1a605468d156e6a8f78f1dc" ON "customers" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7837678f3d750698394a80f70" ON "customers" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7d65d9783ac8299a24d368222" ON "customers" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_625f16be36eec940b817fd6022" ON "customers" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce4257301de587562249d300f8" ON "customers" ("tenantId", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c0d50bb04cf7976e922b5781d" ON "customers" ("tenantId", "phone") `);
        await queryRunner.query(`CREATE TABLE "customer_segments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying(255) NOT NULL, "storeId" character varying(255), "name" character varying(150) NOT NULL, "description" text, "rules" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1509398a6c472bfecd14d9d3152" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f6b294925bd425b86b1fb640f" ON "customer_segments" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_81350f8ac6abf1e31278c0710a" ON "customer_segments" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "customer_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid, "customerId" uuid NOT NULL, "authorId" uuid, "authorName" character varying(100) NOT NULL DEFAULT 'Merchant', "content" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8a41bce1fe0094bd7a9c5266cc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notes_tenantId_customerId" ON "customer_notes" ("tenantId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notes_tenantId" ON "customer_notes" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_notes_customerId" ON "customer_notes" ("customerId") `);
        await queryRunner.query(`CREATE TABLE "customer_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid, "customerId" uuid NOT NULL, "label" character varying(50) NOT NULL DEFAULT 'Home', "recipientName" character varying(100) NOT NULL, "phone" character varying(30) NOT NULL, "addressLine1" text NOT NULL, "addressLine2" text, "area" character varying(100), "thana" character varying(100), "district" character varying(100), "division" character varying(100), "city" character varying(100) NOT NULL DEFAULT 'Dhaka', "postalCode" character varying(20), "country" character varying(100) NOT NULL DEFAULT 'Bangladesh', "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_336bda7b0a0cd04241f719fc834" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_customer_addresses_tenantId_customerId" ON "customer_addresses" ("tenantId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_addresses_tenantId" ON "customer_addresses" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_addresses_customerId" ON "customer_addresses" ("customerId") `);
        await queryRunner.query(`CREATE TABLE "customer_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid, "customerId" uuid NOT NULL, "eventType" character varying(100) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "actorName" character varying(100) NOT NULL DEFAULT 'System', "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_359c4a3763df0f71a998ae7cdf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_customer_activities_tenantId_customerId" ON "customer_activities" ("tenantId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_activities_tenantId" ON "customer_activities" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_activities_customerId" ON "customer_activities" ("customerId") `);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discounttype_enum" AS ENUM('PERCENTAGE', 'FIXED')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "discountType" "public"."coupons_discounttype_enum" NOT NULL DEFAULT 'PERCENTAGE', "discountValue" numeric(10,2) NOT NULL, "minOrderAmount" numeric(10,2) NOT NULL DEFAULT '0', "maxUses" integer NOT NULL DEFAULT '100', "usedCount" integer NOT NULL DEFAULT '0', "expiryDate" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer NOT NULL, "reviewerName" character varying(255) NOT NULL, "reviewerEmail" character varying(255), "comment" text NOT NULL, "images" jsonb DEFAULT '[]', "isVerifiedBuyer" boolean NOT NULL DEFAULT false, "isApproved" boolean NOT NULL DEFAULT false, "productId" uuid NOT NULL, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_67c1501aea1b0633ec441b00bd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ccb3b923ab454a614047f9442" ON "product_reviews" ("isApproved") `);
        await queryRunner.query(`CREATE INDEX "IDX_32edd80d91dff1bc19e79c8f16" ON "product_reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bc3d96c513181275abade8770" ON "product_reviews" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "product_relations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "relatedProductId" uuid NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fba7297af4d3a79b8e511777439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_relations_unique" ON "product_relations" ("tenantId", "productId", "relatedProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_relations_tenant_prod" ON "product_relations" ("tenantId", "productId") `);
        await queryRunner.query(`CREATE TABLE "category_attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "categoryId" uuid NOT NULL, "attributeId" uuid NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f58b128e30a1ad029b32fb79624" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_category_attributes_cat_attr" ON "category_attributes" ("categoryId", "attributeId") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'PAST_DUE', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "planId" uuid NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "currentPeriodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "currentPeriodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "gracePeriodEndsAt" TIMESTAMP WITH TIME ZONE, "pendingPlanId" uuid, "pendingPlanEffectiveAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0c5fe8e5f9f4dd4a8c0134abc9c" UNIQUE ("tenantId"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_invoices_status_enum" AS ENUM('PENDING', 'PAID', 'FAILED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "subscription_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "subscriptionId" uuid NOT NULL, "planId" uuid NOT NULL, "amountBdt" numeric(12,2) NOT NULL, "tranId" character varying(100), "valId" character varying(100), "status" "public"."subscription_invoices_status_enum" NOT NULL DEFAULT 'PENDING', "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9e013e7ff57edb2f8989d5c033" UNIQUE ("tranId"), CONSTRAINT "PK_7050ae7d81f0f0207b8f1cd2efc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."plans_code_enum" AS ENUM('FREE', 'GROWTH', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" "public"."plans_code_enum" NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255) NOT NULL DEFAULT '', "features" jsonb NOT NULL DEFAULT '[]'::jsonb, "displayOrder" integer NOT NULL DEFAULT '0', "monthlyPriceBdt" numeric(12,2) NOT NULL DEFAULT '0', "maxStores" integer, "maxStaffPerStore" integer, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_95f7ef3fc4c31a3545b4d825dd4" UNIQUE ("code"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(50), "subject" character varying(255) NOT NULL, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b74f96eb2edd977ccfba6533293" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "configKey" character varying NOT NULL DEFAULT 'global', "heroContent" jsonb DEFAULT '{}', "pricingPlans" jsonb DEFAULT '[]', "testimonials" jsonb DEFAULT '[]', "faqs" jsonb DEFAULT '[]', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2c312e08f0edcdfbfb17c35067e" UNIQUE ("configKey"), CONSTRAINT "PK_8f9dc7b98d9e8fcb5eeb292bb95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_collections" ("productId" uuid NOT NULL, "collectionId" uuid NOT NULL, CONSTRAINT "PK_f0480fb4be021b4c18de6270e76" PRIMARY KEY ("productId", "collectionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f8e9b2201736fa49753b3f103d" ON "product_collections" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_770acab80a3957898eba6248f1" ON "product_collections" ("collectionId") `);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_ebf3da4043eef0c65debcdf819a" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_a276dea330e561499e4a6e1b309" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_events" ADD CONSTRAINT "FK_c0f8796eab0370f6dc1d8d10db2" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_items" ADD CONSTRAINT "FK_2d7a02e4a660050ca70edd7df66" FOREIGN KEY ("returnId") REFERENCES "returns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_items" ADD CONSTRAINT "FK_cffa12df74a94bc3ccc347379e9" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "returns" ADD CONSTRAINT "FK_b3851bc6d0e2a7ddc7412806a0f" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_689db3835e5550e68d26ca32676" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_notes" ADD CONSTRAINT "FK_22085a1f5dcf10faae9b57afc0a" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consignment_events" ADD CONSTRAINT "FK_d03c1ce69bd88e7834da4cc9121" FOREIGN KEY ("consignmentId") REFERENCES "consignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consignments" ADD CONSTRAINT "FK_2167f911d18d46ed34d07a5f0fd" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_880be96629597e53596e18aa137" FOREIGN KEY ("imageId") REFERENCES "product_images"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_options" ADD CONSTRAINT "FK_efeb226523877ae10559d5f716f" FOREIGN KEY ("attributeId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_6f387b01fd9800591fa425dd203" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_155f225a411a7955058946be337" FOREIGN KEY ("attributeId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_b63d959aba798b87b74bc913792" FOREIGN KEY ("shippingProfileId") REFERENCES "shipping_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" ADD CONSTRAINT "FK_f7d658c94780e9bf3b67fa85f5b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" ADD CONSTRAINT "FK_39e046098ef82b987a36bd56093" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" ADD CONSTRAINT "FK_8ee12ab9f8a00d2763282d9b0eb" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_684badd3999923339489222a0b7" FOREIGN KEY ("fromWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_22928dc6cdfdc43ef470de801f4" FOREIGN KEY ("toWarehouseId") REFERENCES "warehouses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_dda1888315d072547f31dde8b8b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_05715a7ea47e49653f164c0dd8c" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_d76f5767ea35d4c281d2bcac34f" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_aa54c8cb6fa5779fa1c2679b822" FOREIGN KEY ("inventoryStockId") REFERENCES "inventory_stocks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_notes" ADD CONSTRAINT "FK_136ae1445ffdcbb1e0014349b23" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_7bd088b1c8d3506953240ebf030" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_activities" ADD CONSTRAINT "FK_f28a98d65acca98259cb985752d" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_relations" ADD CONSTRAINT "FK_cebb63d42801ecb9fa9bbe19268" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_relations" ADD CONSTRAINT "FK_b1644d3bec669767b8526c860a0" FOREIGN KEY ("relatedProductId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attributes" ADD CONSTRAINT "FK_38209e8493459f8b98aa107be2b" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attributes" ADD CONSTRAINT "FK_4eeba7ff3f73d77a0884341456e" FOREIGN KEY ("attributeId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_collections" ADD CONSTRAINT "FK_f8e9b2201736fa49753b3f103d2" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_collections" ADD CONSTRAINT "FK_770acab80a3957898eba6248f1b" FOREIGN KEY ("collectionId") REFERENCES "collections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_collections" DROP CONSTRAINT "FK_770acab80a3957898eba6248f1b"`);
        await queryRunner.query(`ALTER TABLE "product_collections" DROP CONSTRAINT "FK_f8e9b2201736fa49753b3f103d2"`);
        await queryRunner.query(`ALTER TABLE "category_attributes" DROP CONSTRAINT "FK_4eeba7ff3f73d77a0884341456e"`);
        await queryRunner.query(`ALTER TABLE "category_attributes" DROP CONSTRAINT "FK_38209e8493459f8b98aa107be2b"`);
        await queryRunner.query(`ALTER TABLE "product_relations" DROP CONSTRAINT "FK_b1644d3bec669767b8526c860a0"`);
        await queryRunner.query(`ALTER TABLE "product_relations" DROP CONSTRAINT "FK_cebb63d42801ecb9fa9bbe19268"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d"`);
        await queryRunner.query(`ALTER TABLE "customer_activities" DROP CONSTRAINT "FK_f28a98d65acca98259cb985752d"`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_7bd088b1c8d3506953240ebf030"`);
        await queryRunner.query(`ALTER TABLE "customer_notes" DROP CONSTRAINT "FK_136ae1445ffdcbb1e0014349b23"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_aa54c8cb6fa5779fa1c2679b822"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_d76f5767ea35d4c281d2bcac34f"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_05715a7ea47e49653f164c0dd8c"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_dda1888315d072547f31dde8b8b"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_22928dc6cdfdc43ef470de801f4"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_684badd3999923339489222a0b7"`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" DROP CONSTRAINT "FK_8ee12ab9f8a00d2763282d9b0eb"`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" DROP CONSTRAINT "FK_39e046098ef82b987a36bd56093"`);
        await queryRunner.query(`ALTER TABLE "inventory_stocks" DROP CONSTRAINT "FK_f7d658c94780e9bf3b67fa85f5b"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_b63d959aba798b87b74bc913792"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_155f225a411a7955058946be337"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_6f387b01fd9800591fa425dd203"`);
        await queryRunner.query(`ALTER TABLE "attribute_options" DROP CONSTRAINT "FK_efeb226523877ae10559d5f716f"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_880be96629597e53596e18aa137"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "consignments" DROP CONSTRAINT "FK_2167f911d18d46ed34d07a5f0fd"`);
        await queryRunner.query(`ALTER TABLE "consignment_events" DROP CONSTRAINT "FK_d03c1ce69bd88e7834da4cc9121"`);
        await queryRunner.query(`ALTER TABLE "order_notes" DROP CONSTRAINT "FK_22085a1f5dcf10faae9b57afc0a"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_689db3835e5550e68d26ca32676"`);
        await queryRunner.query(`ALTER TABLE "returns" DROP CONSTRAINT "FK_b3851bc6d0e2a7ddc7412806a0f"`);
        await queryRunner.query(`ALTER TABLE "return_items" DROP CONSTRAINT "FK_cffa12df74a94bc3ccc347379e9"`);
        await queryRunner.query(`ALTER TABLE "return_items" DROP CONSTRAINT "FK_2d7a02e4a660050ca70edd7df66"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "payment_events" DROP CONSTRAINT "FK_c0f8796eab0370f6dc1d8d10db2"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_a276dea330e561499e4a6e1b309"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_ebf3da4043eef0c65debcdf819a"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_770acab80a3957898eba6248f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8e9b2201736fa49753b3f103d"`);
        await queryRunner.query(`DROP TABLE "product_collections"`);
        await queryRunner.query(`DROP TABLE "platform_configs"`);
        await queryRunner.query(`DROP TABLE "contact_messages"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_code_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_category_attributes_cat_attr"`);
        await queryRunner.query(`DROP TABLE "category_attributes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_relations_tenant_prod"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_relations_unique"`);
        await queryRunner.query(`DROP TABLE "product_relations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bc3d96c513181275abade8770"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32edd80d91dff1bc19e79c8f16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ccb3b923ab454a614047f9442"`);
        await queryRunner.query(`DROP TABLE "product_reviews"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discounttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_activities_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_activities_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_activities_tenantId_customerId"`);
        await queryRunner.query(`DROP TABLE "customer_activities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_addresses_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_addresses_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_addresses_tenantId_customerId"`);
        await queryRunner.query(`DROP TABLE "customer_addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notes_customerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notes_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_notes_tenantId_customerId"`);
        await queryRunner.query(`DROP TABLE "customer_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81350f8ac6abf1e31278c0710a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f6b294925bd425b86b1fb640f"`);
        await queryRunner.query(`DROP TABLE "customer_segments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c0d50bb04cf7976e922b5781d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce4257301de587562249d300f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_625f16be36eec940b817fd6022"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7d65d9783ac8299a24d368222"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7837678f3d750698394a80f70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37c1a605468d156e6a8f78f1dc"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`DROP TABLE "email_campaigns"`);
        await queryRunner.query(`DROP TABLE "newsletter_subscribers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_movements_prod"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_movements_tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_movements_var"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_movements_stock"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a3b1bdea06d49c59826fbddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_684badd3999923339489222a0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22928dc6cdfdc43ef470de801f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dda1888315d072547f31dde8b8"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_tenant_prod"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_tenant_wh"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_stocks_tenant_var"`);
        await queryRunner.query(`DROP TABLE "inventory_stocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenant_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenant_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenant_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenant_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_tenant_brand"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_servicedurationunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_servicedeliverytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_digitaldeliverytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_dimensionunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_weightunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_discounttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_taxcategory_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_producttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipping_profiles_tenant"`);
        await queryRunner.query(`DROP TABLE "shipping_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_attr_values_prod_attr"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_attr_values_tenant"`);
        await queryRunner.query(`DROP TABLE "product_attribute_values"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attribute_definitions_tenant_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attribute_definitions_tenant_slug"`);
        await queryRunner.query(`DROP TABLE "attribute_definitions"`);
        await queryRunner.query(`DROP TYPE "public"."attribute_definitions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attribute_options_attr"`);
        await queryRunner.query(`DROP TABLE "attribute_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_variants_prod_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_variants_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_variants_tenant_sku"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_variants_prod_comb"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_images_product_tenant"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_collections_tenant_slug"`);
        await queryRunner.query(`DROP TABLE "collections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_brands_tenant_slug"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8191c898401ab93cb04ce1986"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4492aaaf3bac186ce7ce379a45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0d5731e7002ff4e4b04590a7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be815db99f0960c3f22d13de34"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_courier_integrations_tenant"`);
        await queryRunner.query(`DROP TABLE "courier_integrations"`);
        await queryRunner.query(`DROP TYPE "public"."courier_integrations_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenant_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenant_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenant_cod_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenant_courier"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tenant_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_customer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_consignments_tracking_code"`);
        await queryRunner.query(`DROP TABLE "consignments"`);
        await queryRunner.query(`DROP TYPE "public"."consignments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."consignments_codstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."consignments_courierprovider_enum"`);
        await queryRunner.query(`DROP TABLE "consignment_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e97e38e81aed2eff897173b91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca679bce44a6852cf7538084f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68514ad668da8bf80ddbb1e2c1"`);
        await queryRunner.query(`DROP TABLE "marketing_event_configs"`);
        await queryRunner.query(`DROP TYPE "public"."marketing_event_configs_eventname_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dff5896f08f92a78af04eba720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff909d6e41a974d0a020e30733"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb6f880375d6be6cf4e4871dd3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6b0b0c4b5a362b641155da175"`);
        await queryRunner.query(`DROP TABLE "marketing_event_logs"`);
        await queryRunner.query(`DROP TYPE "public"."marketing_event_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a742ccfc2a97502f2721698b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a6314615c24e8933a35207123"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_617b8a1ad8c7022d950ebb4b90"`);
        await queryRunner.query(`DROP TABLE "marketing_pixels"`);
        await queryRunner.query(`DROP TYPE "public"."marketing_pixels_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."marketing_pixels_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7260711c6f06cde1157910aa62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65acd151236aaa0151aa420c92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc5e38342cac10295c5a9d4550"`);
        await queryRunner.query(`DROP TABLE "abandoned_carts"`);
        await queryRunner.query(`DROP TABLE "order_notes"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_newstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_previousstatus_enum"`);
        await queryRunner.query(`DROP TABLE "returns"`);
        await queryRunner.query(`DROP TYPE "public"."returns_status_enum"`);
        await queryRunner.query(`DROP TABLE "return_items"`);
        await queryRunner.query(`DROP TYPE "public"."return_items_condition_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_events_tenant_payment"`);
        await queryRunner.query(`DROP TABLE "payment_events"`);
        await queryRunner.query(`DROP TYPE "public"."payment_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_gateways_tenant_code"`);
        await queryRunner.query(`DROP TABLE "payment_gateways"`);
        await queryRunner.query(`DROP TYPE "public"."payment_gateways_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_gateways_code_enum"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP TYPE "public"."refunds_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_gateway"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_method"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_customer"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_gateway_enum"`);
        await queryRunner.query(`DROP TABLE "push_notifications"`);
        await queryRunner.query(`DROP TYPE "public"."push_notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "sms_logs"`);
        await queryRunner.query(`DROP TYPE "public"."sms_logs_status_enum"`);
        await queryRunner.query(`DROP TABLE "staff_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_326778db9810dec33ed988b0b9"`);
        await queryRunner.query(`DROP TABLE "store_api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51308fdbb7eebcfecb2973b7b7"`);
        await queryRunner.query(`DROP TABLE "delivery_zones"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TYPE "public"."stores_emaildriver_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_smsdriver_enum"`);
        await queryRunner.query(`DROP TABLE "theme_purchases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4649a70b12d79602a84d3b9ac"`);
        await queryRunner.query(`DROP TABLE "store_webhooks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3921079ff981d52f999a149422"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecbdea919b4d1434fe24302438"`);
        await queryRunner.query(`DROP TABLE "storefront_sessions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
    }

}
