import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncMissingEntityChanges1789407323577 implements MigrationInterface {
    name = 'SyncMissingEntityChanges1789407323577'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_branches_storeId"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_branches_warehouseId"`);
        await queryRunner.query(`ALTER TABLE "pur_purchase_order_lines" DROP CONSTRAINT "FK_pur_purchase_order_lines_purchaseOrderId"`);
        await queryRunner.query(`ALTER TABLE "pur_bill_lines" DROP CONSTRAINT "FK_pur_bill_lines_billId"`);
        await queryRunner.query(`ALTER TABLE "marketing_pixel_page_rules" DROP CONSTRAINT "FK_marketing_pixel_page_rules_pixel"`);
        await queryRunner.query(`ALTER TABLE "marketing_event_logs" DROP CONSTRAINT "FK_marketing_event_logs_pixel"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_fromBranchId"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_toBranchId"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_stock_transfers_variantId"`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" DROP CONSTRAINT "FK_branch_stocks_productId"`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" DROP CONSTRAINT "FK_branch_stocks_variantId"`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" DROP CONSTRAINT "FK_branch_stocks_branchId"`);
        await queryRunner.query(`ALTER TABLE "hr_employees" DROP CONSTRAINT "FK_hr_employees_departmentId"`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" DROP CONSTRAINT "FK_hr_shift_assignments_employeeId"`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" DROP CONSTRAINT "FK_hr_shift_assignments_shiftId"`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" DROP CONSTRAINT "FK_hr_salary_structures_employeeId"`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" DROP CONSTRAINT "FK_hr_payslips_payrollRunId"`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" DROP CONSTRAINT "FK_hr_payslips_employeeId"`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" DROP CONSTRAINT "FK_hr_leave_requests_employeeId"`);
        await queryRunner.query(`ALTER TABLE "hr_expenses" DROP CONSTRAINT "FK_hr_expenses_employeeId"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance" DROP CONSTRAINT "FK_hr_attendance_employeeId"`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" DROP CONSTRAINT "FK_fin_transfers_fromAccount"`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" DROP CONSTRAINT "FK_fin_transfers_toAccount"`);
        await queryRunner.query(`ALTER TABLE "fin_invoice_items" DROP CONSTRAINT "FK_fin_invoice_items_invoice"`);
        await queryRunner.query(`ALTER TABLE "fin_bill_items" DROP CONSTRAINT "FK_fin_bill_items_bill"`);
        await queryRunner.query(`ALTER TABLE "acc_journal_lines" DROP CONSTRAINT "FK_acc_journal_lines_journalEntryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_branches_tenantId_storeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_supplier_payments_storeId_billId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_supplier_payments_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_orderDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_paymentStatus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_billDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_pixels_tenant_store_provider"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_pixel_page_rules_pixel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_pixel_page_rules_tenant_store"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_event_logs_pixel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_event_logs_tenant_store_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_event_logs_tenant_store_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_ad_spends_tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_ad_spends_store"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_ad_spends_tenant_store"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_marketing_ad_spends_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_toBranchId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_fromBranchId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transfers_createdByUserId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acc_journal_entries_storeId_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acc_expenses_storeId_date"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "UQ_branches_storeId_code"`);
        await queryRunner.query(`CREATE TABLE "omnichannel_ai_document_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "documentId" uuid NOT NULL, "chunkIndex" integer NOT NULL, "content" text NOT NULL, "tokenCount" integer NOT NULL DEFAULT '0', "embedding" jsonb, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c3f68e394f8c085b6b27f92d0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d632d149f7682b41a2e1c2cd25" ON "omnichannel_ai_document_chunks" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_76ac483a6ca720133d7e46cc7a" ON "omnichannel_ai_document_chunks" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b4c9ca2d34495a81cedbe1f25" ON "omnichannel_ai_document_chunks" ("documentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_716ffd0f6f3672028d22c8733d" ON "omnichannel_ai_document_chunks" ("tenantId", "storeId", "documentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53b4075b753a67f15b0df0dd46" ON "omnichannel_ai_document_chunks" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE TABLE "omnichannel_ai_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "storeId" uuid NOT NULL, "fileName" character varying(255) NOT NULL, "fileType" character varying(50) NOT NULL DEFAULT 'pdf', "fileSize" integer NOT NULL DEFAULT '0', "fileUrl" text, "status" character varying(50) NOT NULL DEFAULT 'PROCESSING', "chunkCount" integer NOT NULL DEFAULT '0', "errorMessage" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c600c4a4ebf3127317ec922d396" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e693bacfd7af07068a99ee734" ON "omnichannel_ai_documents" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_95d27881f0eb9cc99725fae194" ON "omnichannel_ai_documents" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_acb48951ec9b31c6e62e773479" ON "omnichannel_ai_documents" ("tenantId", "storeId") `);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "encryptedGeminiKey" text`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "encryptedOpenaiKey" text`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "encryptedClaudeKey" text`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "encryptedDeepseekKey" text`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "encryptedGroqKey" text`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ADD "enabledPlatforms" jsonb NOT NULL DEFAULT '{"telegram":true,"whatsapp":true,"instagram":true,"facebook":true,"x":true}'`);
        await queryRunner.query(`ALTER TABLE "crm_leads" ADD "inquiries" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "stores" ALTER COLUMN "checkoutFieldConfig" SET DEFAULT '{"email":{"show":true,"required":false},"address":{"show":true,"required":true},"country":{"show":true,"required":true},"division":{"show":true,"required":true},"district":{"show":true,"required":true},"cityArea":{"show":true,"required":true},"zipCode":{"show":true,"required":false},"orderNote":{"show":true,"required":false}}'`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ALTER COLUMN "model" SET DEFAULT 'gemini-2.5-flash'`);
        await queryRunner.query(`ALTER TABLE "consignments" ALTER COLUMN "parcelWeight" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TYPE "public"."fin_source_type_enum" RENAME TO "fin_source_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."fin_transactions_sourcetype_enum" AS ENUM('MANUAL', 'ORDER', 'INVOICE', 'BILL', 'HR_EXPENSE', 'PAYROLL', 'TRANSFER', 'ADJUSTMENT')`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" TYPE "public"."fin_transactions_sourcetype_enum" USING "sourceType"::"text"::"public"."fin_transactions_sourcetype_enum"`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" SET DEFAULT 'MANUAL'`);
        await queryRunner.query(`DROP TYPE "public"."fin_source_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "features" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`CREATE INDEX "IDX_ba10e1dc33984996642ef890d4" ON "branches" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_supplier_payments_storeId_supplierId" ON "pur_supplier_payments" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_supplier_payments_storeId_billId" ON "pur_supplier_payments" ("billId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_supplierId" ON "pur_purchase_orders" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_orderDate" ON "pur_purchase_orders" ("orderDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_status" ON "pur_purchase_orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_supplierId" ON "pur_bills" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_billDate" ON "pur_bills" ("billDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_paymentStatus" ON "pur_bills" ("paymentStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_23d02cf6e67e4c73b59f1cdcbb" ON "marketing_pixels" ("tenantId", "storeId", "provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a798f4dac3a0efa45f95879e" ON "marketing_pixel_page_rules" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_44c634496aa68502e122689cab" ON "marketing_pixel_page_rules" ("pixelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce2eedf74356704d37822479e3" ON "marketing_event_logs" ("pixelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37feb02189cead14ff29dda390" ON "marketing_event_logs" ("tenantId", "storeId", "orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac447870202e3fbc5d7a06a547" ON "marketing_event_logs" ("tenantId", "storeId", "eventName") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac05bd9fe2d520fa85baea88af" ON "marketing_ad_spends" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8973660bdc976bed670e46a6a0" ON "marketing_ad_spends" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_931135cdef6aa3614bbbd87bf8" ON "marketing_ad_spends" ("tenantId", "storeId", "dimension", "periodStart") `);
        await queryRunner.query(`CREATE INDEX "IDX_15ac3462351f175e4060a72878" ON "marketing_ad_spends" ("tenantId", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5759e8891a87a893ff8adde241" ON "stock_transfers" ("toBranchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_064e80efd849968fabb7121925" ON "stock_transfers" ("fromBranchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_acc_journal_entries_storeId_date" ON "acc_journal_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_acc_expenses_storeId_date" ON "acc_expenses" ("date") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_78d545440c190869e8278b99b35" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pur_purchase_order_lines" ADD CONSTRAINT "FK_7a679fd21ec6e2320917d84dcab" FOREIGN KEY ("purchaseOrderId") REFERENCES "pur_purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pur_bill_lines" ADD CONSTRAINT "FK_5eb2c63d416ed02452d95fce0f3" FOREIGN KEY ("billId") REFERENCES "pur_bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_document_chunks" ADD CONSTRAINT "FK_5b4c9ca2d34495a81cedbe1f25c" FOREIGN KEY ("documentId") REFERENCES "omnichannel_ai_documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_0912b31b8f410d9d6df3b7a04c3" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" ADD CONSTRAINT "FK_36251f9e6b26474a9fa3abd705a" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" ADD CONSTRAINT "FK_8c9c4dcf056b939829e08052e51" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employees" ADD CONSTRAINT "FK_dd99005bfc2a9957e69510bc539" FOREIGN KEY ("departmentId") REFERENCES "hr_departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" ADD CONSTRAINT "FK_2fe356a8cdb82391e32faec981b" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" ADD CONSTRAINT "FK_d9cfd0746eb93f371b75243eb26" FOREIGN KEY ("shiftId") REFERENCES "hr_shifts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" ADD CONSTRAINT "FK_4a4b342518a2eceeed26d97ff31" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" ADD CONSTRAINT "FK_9cd16a3d99fbc9f34ab412d80d0" FOREIGN KEY ("payrollRunId") REFERENCES "hr_payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" ADD CONSTRAINT "FK_c5102c3c9841e18d50f4fa8eb09" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" ADD CONSTRAINT "FK_f59d98d27750afddb0c514f2464" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_expenses" ADD CONSTRAINT "FK_69ffff9deebae5fc8fb2bb4c615" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance" ADD CONSTRAINT "FK_40e91917c3482ae964802ef69fb" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" ADD CONSTRAINT "FK_fe1b4ba03b84ec4050357525c80" FOREIGN KEY ("fromAccountId") REFERENCES "fin_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" ADD CONSTRAINT "FK_5bec82fc7f1efcce6301c3da604" FOREIGN KEY ("toAccountId") REFERENCES "fin_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ADD CONSTRAINT "FK_060fadec355ba3e7149f8cd46a9" FOREIGN KEY ("accountId") REFERENCES "fin_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ADD CONSTRAINT "FK_df8354537f0b3f7c6eaee7bf302" FOREIGN KEY ("toAccountId") REFERENCES "fin_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ADD CONSTRAINT "FK_f96b066ee4b1f4d5506a2e5a7c8" FOREIGN KEY ("categoryId") REFERENCES "fin_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_invoice_items" ADD CONSTRAINT "FK_8959746e0a040ae416f0039b59e" FOREIGN KEY ("invoiceId") REFERENCES "fin_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_bill_items" ADD CONSTRAINT "FK_c81ec5c34d813e2520d410f2824" FOREIGN KEY ("billId") REFERENCES "fin_bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "acc_journal_lines" ADD CONSTRAINT "FK_1042ac35b52449056b853986498" FOREIGN KEY ("journalEntryId") REFERENCES "acc_journal_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "acc_journal_lines" DROP CONSTRAINT "FK_1042ac35b52449056b853986498"`);
        await queryRunner.query(`ALTER TABLE "fin_bill_items" DROP CONSTRAINT "FK_c81ec5c34d813e2520d410f2824"`);
        await queryRunner.query(`ALTER TABLE "fin_invoice_items" DROP CONSTRAINT "FK_8959746e0a040ae416f0039b59e"`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" DROP CONSTRAINT "FK_f96b066ee4b1f4d5506a2e5a7c8"`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" DROP CONSTRAINT "FK_df8354537f0b3f7c6eaee7bf302"`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" DROP CONSTRAINT "FK_060fadec355ba3e7149f8cd46a9"`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" DROP CONSTRAINT "FK_5bec82fc7f1efcce6301c3da604"`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" DROP CONSTRAINT "FK_fe1b4ba03b84ec4050357525c80"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance" DROP CONSTRAINT "FK_40e91917c3482ae964802ef69fb"`);
        await queryRunner.query(`ALTER TABLE "hr_expenses" DROP CONSTRAINT "FK_69ffff9deebae5fc8fb2bb4c615"`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" DROP CONSTRAINT "FK_f59d98d27750afddb0c514f2464"`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" DROP CONSTRAINT "FK_c5102c3c9841e18d50f4fa8eb09"`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" DROP CONSTRAINT "FK_9cd16a3d99fbc9f34ab412d80d0"`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" DROP CONSTRAINT "FK_4a4b342518a2eceeed26d97ff31"`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" DROP CONSTRAINT "FK_d9cfd0746eb93f371b75243eb26"`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" DROP CONSTRAINT "FK_2fe356a8cdb82391e32faec981b"`);
        await queryRunner.query(`ALTER TABLE "hr_employees" DROP CONSTRAINT "FK_dd99005bfc2a9957e69510bc539"`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" DROP CONSTRAINT "FK_8c9c4dcf056b939829e08052e51"`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" DROP CONSTRAINT "FK_36251f9e6b26474a9fa3abd705a"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_0912b31b8f410d9d6df3b7a04c3"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_document_chunks" DROP CONSTRAINT "FK_5b4c9ca2d34495a81cedbe1f25c"`);
        await queryRunner.query(`ALTER TABLE "pur_bill_lines" DROP CONSTRAINT "FK_5eb2c63d416ed02452d95fce0f3"`);
        await queryRunner.query(`ALTER TABLE "pur_purchase_order_lines" DROP CONSTRAINT "FK_7a679fd21ec6e2320917d84dcab"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_78d545440c190869e8278b99b35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acc_expenses_storeId_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acc_journal_entries_storeId_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_064e80efd849968fabb7121925"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5759e8891a87a893ff8adde241"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15ac3462351f175e4060a72878"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_931135cdef6aa3614bbbd87bf8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8973660bdc976bed670e46a6a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac05bd9fe2d520fa85baea88af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac447870202e3fbc5d7a06a547"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37feb02189cead14ff29dda390"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce2eedf74356704d37822479e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44c634496aa68502e122689cab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a798f4dac3a0efa45f95879e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23d02cf6e67e4c73b59f1cdcbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_paymentStatus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_billDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_bills_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_orderDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_purchase_orders_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_supplier_payments_storeId_billId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pur_supplier_payments_storeId_supplierId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba10e1dc33984996642ef890d4"`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "features" SET DEFAULT '[]'`);
        await queryRunner.query(`CREATE TYPE "public"."fin_source_type_enum_old" AS ENUM('MANUAL', 'ORDER', 'INVOICE', 'BILL', 'HR_EXPENSE', 'PAYROLL', 'TRANSFER', 'ADJUSTMENT')`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" TYPE "public"."fin_source_type_enum_old" USING "sourceType"::"text"::"public"."fin_source_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "fin_transactions" ALTER COLUMN "sourceType" SET DEFAULT 'MANUAL'`);
        await queryRunner.query(`DROP TYPE "public"."fin_transactions_sourcetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."fin_source_type_enum_old" RENAME TO "fin_source_type_enum"`);
        await queryRunner.query(`ALTER TABLE "consignments" ALTER COLUMN "parcelWeight" SET DEFAULT 0.5`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" ALTER COLUMN "model" SET DEFAULT 'gemini-1.5-flash'`);
        await queryRunner.query(`ALTER TABLE "stores" ALTER COLUMN "checkoutFieldConfig" SET DEFAULT '{"email": {"show": true, "required": false}, "address": {"show": true, "required": true}, "country": {"show": true, "required": true}, "zipCode": {"show": true, "required": false}, "cityArea": {"show": true, "required": true}, "district": {"show": true, "required": true}, "division": {"show": true, "required": true}, "orderNote": {"show": true, "required": false}}'`);
        await queryRunner.query(`ALTER TABLE "crm_leads" DROP COLUMN "inquiries"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "enabledPlatforms"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "encryptedGroqKey"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "encryptedDeepseekKey"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "encryptedClaudeKey"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "encryptedOpenaiKey"`);
        await queryRunner.query(`ALTER TABLE "omnichannel_ai_configs" DROP COLUMN "encryptedGeminiKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acb48951ec9b31c6e62e773479"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95d27881f0eb9cc99725fae194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e693bacfd7af07068a99ee734"`);
        await queryRunner.query(`DROP TABLE "omnichannel_ai_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53b4075b753a67f15b0df0dd46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_716ffd0f6f3672028d22c8733d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b4c9ca2d34495a81cedbe1f25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76ac483a6ca720133d7e46cc7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d632d149f7682b41a2e1c2cd25"`);
        await queryRunner.query(`DROP TABLE "omnichannel_ai_document_chunks"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "UQ_branches_storeId_code" UNIQUE ("storeId", "code")`);
        await queryRunner.query(`CREATE INDEX "IDX_acc_expenses_storeId_date" ON "acc_expenses" ("date", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_acc_journal_entries_storeId_date" ON "acc_journal_entries" ("date", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_createdByUserId" ON "stock_transfers" ("createdByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_fromBranchId" ON "stock_transfers" ("fromBranchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transfers_toBranchId" ON "stock_transfers" ("toBranchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_ad_spends_lookup" ON "marketing_ad_spends" ("dimension", "periodStart", "storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_ad_spends_tenant_store" ON "marketing_ad_spends" ("storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_ad_spends_store" ON "marketing_ad_spends" ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_ad_spends_tenant" ON "marketing_ad_spends" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_event_logs_tenant_store_event" ON "marketing_event_logs" ("eventName", "storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_event_logs_tenant_store_order" ON "marketing_event_logs" ("orderId", "storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_event_logs_pixel" ON "marketing_event_logs" ("pixelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_pixel_page_rules_tenant_store" ON "marketing_pixel_page_rules" ("storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_pixel_page_rules_pixel" ON "marketing_pixel_page_rules" ("pixelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_marketing_pixels_tenant_store_provider" ON "marketing_pixels" ("provider", "storeId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_billDate" ON "pur_bills" ("billDate", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_supplierId" ON "pur_bills" ("storeId", "supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_bills_storeId_paymentStatus" ON "pur_bills" ("paymentStatus", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_orderDate" ON "pur_purchase_orders" ("orderDate", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_supplierId" ON "pur_purchase_orders" ("storeId", "supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_purchase_orders_storeId_status" ON "pur_purchase_orders" ("status", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_supplier_payments_storeId_supplierId" ON "pur_supplier_payments" ("storeId", "supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pur_supplier_payments_storeId_billId" ON "pur_supplier_payments" ("billId", "storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_branches_tenantId_storeId" ON "branches" ("storeId", "tenantId") `);
        await queryRunner.query(`ALTER TABLE "acc_journal_lines" ADD CONSTRAINT "FK_acc_journal_lines_journalEntryId" FOREIGN KEY ("journalEntryId") REFERENCES "acc_journal_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_bill_items" ADD CONSTRAINT "FK_fin_bill_items_bill" FOREIGN KEY ("billId") REFERENCES "fin_bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_invoice_items" ADD CONSTRAINT "FK_fin_invoice_items_invoice" FOREIGN KEY ("invoiceId") REFERENCES "fin_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" ADD CONSTRAINT "FK_fin_transfers_toAccount" FOREIGN KEY ("toAccountId") REFERENCES "fin_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_transfers" ADD CONSTRAINT "FK_fin_transfers_fromAccount" FOREIGN KEY ("fromAccountId") REFERENCES "fin_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance" ADD CONSTRAINT "FK_hr_attendance_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_expenses" ADD CONSTRAINT "FK_hr_expenses_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" ADD CONSTRAINT "FK_hr_leave_requests_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" ADD CONSTRAINT "FK_hr_payslips_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payslips" ADD CONSTRAINT "FK_hr_payslips_payrollRunId" FOREIGN KEY ("payrollRunId") REFERENCES "hr_payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" ADD CONSTRAINT "FK_hr_salary_structures_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" ADD CONSTRAINT "FK_hr_shift_assignments_shiftId" FOREIGN KEY ("shiftId") REFERENCES "hr_shifts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_shift_assignments" ADD CONSTRAINT "FK_hr_shift_assignments_employeeId" FOREIGN KEY ("employeeId") REFERENCES "hr_employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employees" ADD CONSTRAINT "FK_hr_employees_departmentId" FOREIGN KEY ("departmentId") REFERENCES "hr_departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" ADD CONSTRAINT "FK_branch_stocks_branchId" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" ADD CONSTRAINT "FK_branch_stocks_variantId" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_stocks" ADD CONSTRAINT "FK_branch_stocks_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_variantId" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_toBranchId" FOREIGN KEY ("toBranchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_stock_transfers_fromBranchId" FOREIGN KEY ("fromBranchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketing_event_logs" ADD CONSTRAINT "FK_marketing_event_logs_pixel" FOREIGN KEY ("pixelId") REFERENCES "marketing_pixels"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketing_pixel_page_rules" ADD CONSTRAINT "FK_marketing_pixel_page_rules_pixel" FOREIGN KEY ("pixelId") REFERENCES "marketing_pixels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pur_bill_lines" ADD CONSTRAINT "FK_pur_bill_lines_billId" FOREIGN KEY ("billId") REFERENCES "pur_bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pur_purchase_order_lines" ADD CONSTRAINT "FK_pur_purchase_order_lines_purchaseOrderId" FOREIGN KEY ("purchaseOrderId") REFERENCES "pur_purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_branches_warehouseId" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_branches_storeId" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
