export type AdminRole = 
  | 'SUPER_ADMIN' 
  | 'SUPPORT_ADMIN' 
  | 'FINANCE_ADMIN' 
  | 'OPERATIONS_ADMIN' 
  | 'DEVOPS_ADMIN' 
  | 'READ_ONLY_AUDITOR';

export const ADMIN_PERMISSIONS = {
  FINANCE_READ: 'admin.finance.read',
  FINANCE_MANAGE: 'admin.finance.manage',
  STORES_READ: 'admin.stores.read',
  STORES_MANAGE: 'admin.stores.manage',
  ORDERS_READ: 'admin.orders.read',
  INFRASTRUCTURE_READ: 'admin.infrastructure.read',
  INFRASTRUCTURE_MANAGE: 'admin.infrastructure.manage',
  AUDIT_READ: 'admin.audit.read',
  CMS_MANAGE: 'admin.cms.manage',
} as const;

export const ROLE_PERMISSION_MAP: Record<AdminRole, string[]> = {
  SUPER_ADMIN: Object.values(ADMIN_PERMISSIONS),
  FINANCE_ADMIN: [
    ADMIN_PERMISSIONS.FINANCE_READ,
    ADMIN_PERMISSIONS.FINANCE_MANAGE,
    ADMIN_PERMISSIONS.STORES_READ,
    ADMIN_PERMISSIONS.ORDERS_READ,
  ],
  SUPPORT_ADMIN: [
    ADMIN_PERMISSIONS.STORES_READ,
    ADMIN_PERMISSIONS.STORES_MANAGE,
    ADMIN_PERMISSIONS.ORDERS_READ,
  ],
  OPERATIONS_ADMIN: [
    ADMIN_PERMISSIONS.STORES_READ,
    ADMIN_PERMISSIONS.STORES_MANAGE,
    ADMIN_PERMISSIONS.ORDERS_READ,
    ADMIN_PERMISSIONS.CMS_MANAGE,
  ],
  DEVOPS_ADMIN: [
    ADMIN_PERMISSIONS.INFRASTRUCTURE_READ,
    ADMIN_PERMISSIONS.INFRASTRUCTURE_MANAGE,
    ADMIN_PERMISSIONS.AUDIT_READ,
  ],
  READ_ONLY_AUDITOR: [
    ADMIN_PERMISSIONS.FINANCE_READ,
    ADMIN_PERMISSIONS.STORES_READ,
    ADMIN_PERMISSIONS.ORDERS_READ,
    ADMIN_PERMISSIONS.INFRASTRUCTURE_READ,
    ADMIN_PERMISSIONS.AUDIT_READ,
  ],
};
