import {
  PlanKpiItem,
  PlanRecord,
  PlanDonutItem,
  PlanHighlightItem,
  PlanRecentChangeItem,
  PlanFeatureCategory,
  PlanLimitsSummary,
  PlanPerformanceStats,
} from './types';

export const PLANS_KPIS: PlanKpiItem[] = [
  {
    id: 'total-plans',
    title: 'Total Plans',
    value: '5',
    subtext: 'Active plans',
    iconType: 'total',
  },
  {
    id: 'active-plans',
    title: 'Active Plans',
    value: '4',
    subtext: 'Visible to merchants',
    iconType: 'active',
  },
  {
    id: 'inactive-plans',
    title: 'Inactive Plans',
    value: '1',
    subtext: 'Not visible to merchants',
    iconType: 'inactive',
  },
  {
    id: 'most-popular',
    title: 'Most Popular Plan',
    value: 'Growth',
    subtext: '842 merchants',
    iconType: 'popular',
  },
  {
    id: 'mrr',
    title: 'MRR (Monthly)',
    value: '৳18,40,000',
    subtext: 'From all active plans',
    iconType: 'mrr',
  },
];

const DEFAULT_GROWTH_FEATURES: PlanFeatureCategory[] = [
  {
    category: 'Core',
    items: [
      {
        id: 'f-store',
        name: 'Online Store',
        iconName: 'store',
        included: true,
        details: 'Create and manage your online store',
      },
      {
        id: 'f-domain',
        name: 'Custom Domain',
        iconName: 'globe',
        included: true,
        details: 'Connect your own domain',
      },
      {
        id: 'f-ssl',
        name: 'SSL Certificate',
        iconName: 'shield',
        included: true,
        details: 'Free SSL certificate for your domain',
      },
      {
        id: 'f-staff',
        name: 'Staff Accounts',
        iconName: 'users',
        included: 10,
        details: 'Number of staff accounts you can add',
      },
    ],
  },
  {
    category: 'Products',
    items: [
      {
        id: 'f-prod-limit',
        name: 'Product Limit',
        iconName: 'package',
        included: '10,000',
        details: 'Total number of products',
      },
      {
        id: 'f-prod-variants',
        name: 'Product Variants',
        iconName: 'layers',
        included: 'Unlimited',
        details: 'Unlimited variants for each product',
      },
      {
        id: 'f-digital-prod',
        name: 'Digital Products',
        iconName: 'download',
        included: true,
        details: 'Sell digital products and downloads',
      },
    ],
  },
  {
    category: 'Orders',
    items: [
      {
        id: 'f-orders-limit',
        name: 'Monthly Orders Limit',
        iconName: 'shopping-bag',
        included: '2,000',
        details: 'Maximum orders per month',
      },
      {
        id: 'f-order-export',
        name: 'Order Export',
        iconName: 'file-down',
        included: true,
        details: 'Export orders in CSV format',
      },
    ],
  },
  {
    category: 'Marketing',
    items: [
      {
        id: 'f-discounts',
        name: 'Discounts & Coupons',
        iconName: 'tag',
        included: true,
        details: 'Create discount coupons and offers',
      },
      {
        id: 'f-email',
        name: 'Email Marketing',
        iconName: 'mail',
        included: '10,000 / month',
        details: 'Monthly email send limit',
      },
    ],
  },
];

export const INITIAL_PLANS: PlanRecord[] = [
  {
    id: 'plan-growth',
    name: 'Growth',
    code: 'GROWTH',
    subtitle: 'For growing businesses that need more power and advanced features.',
    featuresCountText: '18 features',
    iconType: 'growth',
    iconBg: 'bg-blue-600',
    price: '৳2,500',
    yearlyPrice: '৳25,000',
    yearlyDiscount: 'Save 17%',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    trialDays: 14,
    trialAvailable: true,
    visibility: 'Visible to merchants',
    merchantsCount: '842',
    merchantsShare: '(33.1%)',
    mrr: '৳9,80,000',
    mrrShare: '(19.6%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    updatedAt: {
      date: 'Aug 10, 2026',
      time: '02:15 PM',
    },
    description:
      'The Growth plan is perfect for growing businesses. It includes advanced features, higher limits, and priority support to help you scale faster.\n\nIdeal for businesses that are expanding their operations and need more power.',
    featuresUsed: 18,
    featuresTotal: 50,
    whatsIncluded: [
      'Everything in Starter Plan',
      'Advanced reports & analytics',
      'Abandoned cart recovery',
      'Priority email & chat support',
      'Advanced discount rules',
      'POS access',
      'API access',
      'Multiple store locations',
    ],
    featureCategories: DEFAULT_GROWTH_FEATURES,
    performance: {
      merchants: 842,
      merchantsGrowth: '18.3%',
      newSubscriptions: 128,
      newSubscriptionsGrowth: '15.7%',
      cancelled: 14,
      cancelledGrowth: '12.5%',
      mrr: '৳9,80,000',
      mrrGrowth: '19.6%',
    },
    limitsSummary: {
      stores: 5,
      products: '10,000',
      staffAccounts: 10,
      monthlyOrders: '2,000',
      storage: '50 GB',
      bandwidth: '200 GB / month',
      emailSends: '10,000 / month',
      customDomain: true,
      apiAccess: true,
    },
    addons: [
      {
        id: 'addon-sms',
        name: 'SMS Notification Bundle',
        description: '5,000 transactional & promotional SMS messages',
        price: '৳1,200',
        billingPeriod: '/ pack',
        isEnabled: true,
      },
      {
        id: 'addon-storage',
        name: 'Extra Cloud Storage (50 GB)',
        description: 'Additional high-speed CDN asset storage for product videos & files',
        price: '৳800',
        billingPeriod: '/ month',
        isEnabled: true,
      },
      {
        id: 'addon-pos',
        name: 'Dedicated POS Terminal License',
        description: 'Extra counter station for in-store barcode & receipt printing',
        price: '৳1,000',
        billingPeriod: '/ terminal',
        isEnabled: true,
      },
      {
        id: 'addon-priority',
        name: 'Dedicated Account Manager',
        description: 'Direct phone & WhatsApp support with custom migration assistance',
        price: '৳3,500',
        billingPeriod: '/ month',
        isEnabled: false,
      },
    ],
    permissions: [
      {
        id: 'perm-storefront',
        name: 'Custom Theme Code & CSS',
        category: 'Storefront',
        allowed: true,
        description: 'Full code editor access for Liquid/React storefront themes',
      },
      {
        id: 'perm-analytics',
        name: 'Advanced Business Intelligence',
        category: 'Analytics',
        allowed: true,
        description: 'Cohort analysis, customer LTV, and hourly conversion metrics',
      },
      {
        id: 'perm-api',
        name: 'Developer API & Webhooks',
        category: 'Integrations',
        allowed: true,
        description: 'Generate production API keys with rate limits up to 200 req/min',
      },
      {
        id: 'perm-pos',
        name: 'Retail POS Cashier Access',
        category: 'Retail POS',
        allowed: true,
        description: 'Multi-device barcode scanning and offline cash register sync',
      },
      {
        id: 'perm-whitelabel',
        name: 'Full White-label Checkout',
        category: 'Branding',
        allowed: false,
        description: 'Remove all "Powered by EasyCommerce" footers across domains',
      },
    ],
    history: [
      {
        id: 'hist-1',
        title: 'Monthly Order Limit Increased',
        description: 'Quota raised from 1,500 to 2,000 orders/month',
        timestamp: 'Aug 10, 2026 02:15 PM',
        actor: 'Platform Admin (superadmin@easyce.com)',
        type: 'update',
      },
      {
        id: 'hist-2',
        title: 'Added Abandoned Cart Feature',
        description: 'Enabled automatic cart recovery SMS/Email triggers',
        timestamp: 'Jul 24, 2026 11:20 AM',
        actor: 'Sarah Jenkins (Product Lead)',
        type: 'feature',
      },
      {
        id: 'hist-3',
        title: 'Annual Pricing Discount Introduced',
        description: '17% discount applied for yearly advance billing',
        timestamp: 'Jul 15, 2026 04:45 PM',
        actor: 'Tanvir Hossain (Billing Admin)',
        type: 'price',
      },
      {
        id: 'hist-4',
        title: 'Growth Plan Initial Creation',
        description: 'Plan created and published to merchant portal',
        timestamp: 'Jul 10, 2026 10:30 AM',
        actor: 'Platform Admin (superadmin@easyce.com)',
        type: 'create',
      },
    ],
  },
  {
    id: 'plan-starter',
    name: 'Starter',
    code: 'STARTER',
    subtitle: 'Perfect for new businesses getting started with online sales.',
    featuresCountText: '8 features',
    iconType: 'starter',
    iconBg: 'bg-emerald-600',
    price: '৳1,000',
    yearlyPrice: '৳10,000',
    yearlyDiscount: 'Save 16%',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    trialDays: 7,
    trialAvailable: true,
    visibility: 'Visible to merchants',
    merchantsCount: '1,240',
    merchantsShare: '(48.7%)',
    mrr: '৳12,40,000',
    mrrShare: '(24.8%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    updatedAt: {
      date: 'Aug 05, 2026',
      time: '11:15 AM',
    },
    description: 'Perfect for new merchants who are starting their digital e-commerce journey.',
    featuresUsed: 8,
    featuresTotal: 50,
    whatsIncluded: [
      'Online Storefront',
      'Free Subdomain',
      'SSL Certificate',
      'Basic Order Analytics',
      'Standard Payment Gateways',
      'Email Support (48h response)',
    ],
    featureCategories: DEFAULT_GROWTH_FEATURES,
    performance: {
      merchants: 1240,
      merchantsGrowth: '12.4%',
      newSubscriptions: 180,
      newSubscriptionsGrowth: '9.2%',
      cancelled: 28,
      cancelledGrowth: '5.1%',
      mrr: '৳12,40,000',
      mrrGrowth: '14.0%',
    },
    limitsSummary: {
      stores: 1,
      products: '500',
      staffAccounts: 2,
      monthlyOrders: '300',
      storage: '5 GB',
      bandwidth: '20 GB / month',
      emailSends: '1,000 / month',
      customDomain: true,
      apiAccess: false,
    },
  },
  {
    id: 'plan-business',
    name: 'Business',
    code: 'BUSINESS',
    subtitle: 'Advanced tools and higher quotas for fast-scaling multi-channel teams.',
    featuresCountText: '28 features',
    iconType: 'business',
    iconBg: 'bg-amber-500',
    price: '৳5,000',
    yearlyPrice: '৳50,000',
    yearlyDiscount: 'Save 17%',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    trialDays: 14,
    trialAvailable: true,
    visibility: 'Visible to merchants',
    merchantsCount: '328',
    merchantsShare: '(12.9%)',
    mrr: '৳5,00,000',
    mrrShare: '(10.0%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    updatedAt: {
      date: 'Aug 08, 2026',
      time: '04:20 PM',
    },
    description: 'Tailored for high-volume retailers needing API, ERP integrations, and multi-location warehouses.',
    featuresUsed: 28,
    featuresTotal: 50,
    whatsIncluded: [
      'Everything in Growth Plan',
      'Multi-warehouse Inventory',
      'Advanced Automation Flows',
      'Dedicated Webhook Endpoints',
      'Staff Role Customization',
      'Priority Phone Support',
    ],
    featureCategories: DEFAULT_GROWTH_FEATURES,
    performance: {
      merchants: 328,
      merchantsGrowth: '22.1%',
      newSubscriptions: 45,
      newSubscriptionsGrowth: '18.4%',
      cancelled: 4,
      cancelledGrowth: '2.0%',
      mrr: '৳5,00,000',
      mrrGrowth: '21.5%',
    },
    limitsSummary: {
      stores: 15,
      products: '50,000',
      staffAccounts: 30,
      monthlyOrders: '10,000',
      storage: '200 GB',
      bandwidth: '1 TB / month',
      emailSends: '50,000 / month',
      customDomain: true,
      apiAccess: true,
    },
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise',
    code: 'ENTERPRISE',
    subtitle: 'Dedicated high-performance infrastructure, custom SLA, and limitless scalability.',
    featuresCountText: '40+ features',
    iconType: 'enterprise',
    iconBg: 'bg-purple-600',
    price: '৳10,000',
    yearlyPrice: '৳1,00,000',
    yearlyDiscount: 'Save 17%',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    trialDays: 30,
    trialAvailable: true,
    visibility: 'Visible to merchants',
    merchantsCount: '56',
    merchantsShare: '(2.2%)',
    mrr: '৳56,000',
    mrrShare: '(1.1%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    updatedAt: {
      date: 'Aug 01, 2026',
      time: '09:00 AM',
    },
    description: 'Dedicated infrastructure, 99.99% uptime SLA guarantee, custom API limits, and white-label checkout.',
    featuresUsed: 42,
    featuresTotal: 50,
    whatsIncluded: [
      'Everything in Business Plan',
      'White-label Checkout & Branding',
      'Unlimited Staff Accounts',
      'Dedicated Server Cluster',
      'Custom SLA 99.99% Uptime',
      '24/7 Dedicated Account Lead',
    ],
    featureCategories: DEFAULT_GROWTH_FEATURES,
    performance: {
      merchants: 56,
      merchantsGrowth: '31.0%',
      newSubscriptions: 12,
      newSubscriptionsGrowth: '25.0%',
      cancelled: 0,
      cancelledGrowth: '0%',
      mrr: '৳56,000',
      mrrGrowth: '29.8%',
    },
    limitsSummary: {
      stores: 'Unlimited',
      products: 'Unlimited',
      staffAccounts: 'Unlimited',
      monthlyOrders: 'Unlimited',
      storage: '1 TB',
      bandwidth: '5 TB / month',
      emailSends: '2,00,000 / month',
      customDomain: true,
      apiAccess: true,
    },
  },
  {
    id: 'plan-custom',
    name: 'Custom',
    code: 'CUSTOM',
    subtitle: 'Bespoke custom plan tailored to unique enterprise requirements.',
    featuresCountText: 'Custom features',
    iconType: 'custom',
    iconBg: 'bg-slate-500',
    price: 'Custom',
    yearlyPrice: 'Custom',
    yearlyDiscount: 'Negotiable',
    billingPeriod: '/ month',
    billingCycle: 'Custom',
    trialDays: 0,
    trialAvailable: false,
    visibility: 'Hidden from storefronts',
    merchantsCount: '-',
    merchantsShare: '(0%)',
    mrr: '৳0',
    mrrShare: '(0%)',
    status: 'Inactive',
    createdAt: {
      date: 'Jun 15, 2026',
      time: '02:15 PM',
    },
    updatedAt: {
      date: 'Jun 15, 2026',
      time: '02:15 PM',
    },
    description: 'Bespoke configuration negotiated and designed with our enterprise architecture team.',
    featuresUsed: 15,
    featuresTotal: 50,
    whatsIncluded: [
      'Custom SLA agreement',
      'Custom database partitioning',
      'On-premise / private cloud deploy',
      'Custom payment integrations',
    ],
    featureCategories: DEFAULT_GROWTH_FEATURES,
    performance: {
      merchants: 0,
      merchantsGrowth: '0%',
      newSubscriptions: 0,
      newSubscriptionsGrowth: '0%',
      cancelled: 0,
      cancelledGrowth: '0%',
      mrr: '৳0',
      mrrGrowth: '0%',
    },
    limitsSummary: {
      stores: 'Custom',
      products: 'Custom',
      staffAccounts: 'Custom',
      monthlyOrders: 'Custom',
      storage: 'Custom',
      bandwidth: 'Custom',
      emailSends: 'Custom',
      customDomain: true,
      apiAccess: true,
    },
  },
];

export const PLAN_DONUT_DATA: PlanDonutItem[] = [
  { name: 'Starter', value: 1240, percentage: '48.7%', color: '#10B981' },
  { name: 'Growth', value: 842, percentage: '33.1%', color: '#3B82F6' },
  { name: 'Business', value: 328, percentage: '12.9%', color: '#F59E0B' },
  { name: 'Enterprise', value: 56, percentage: '2.2%', color: '#8B5CF6' },
  { name: 'Custom', value: 118, percentage: '4.6%', color: '#64748B' },
];

export const PLAN_HIGHLIGHTS: PlanHighlightItem[] = [
  {
    id: 'h-1',
    tag: 'Highest MRR',
    planName: 'Growth Plan',
    statValue: '৳9,80,000 / month',
    tagColor: 'green',
  },
  {
    id: 'h-2',
    tag: 'Most Merchants',
    planName: 'Starter Plan',
    statValue: '1,240 merchants',
    tagColor: 'blue',
  },
  {
    id: 'h-3',
    tag: 'Highest ARPU',
    planName: 'Business Plan',
    statValue: '৳15,244 / month',
    tagColor: 'amber',
  },
  {
    id: 'h-4',
    tag: 'Best Conversion',
    planName: 'Growth Plan',
    statValue: '23.5% conversion',
    tagColor: 'purple',
  },
];

export const PLAN_RECENT_CHANGES: PlanRecentChangeItem[] = [
  {
    id: 'c-1',
    title: 'Business plan updated',
    description: 'Updated features and limits',
    timeAgo: '2 hours ago',
    iconType: 'edit',
  },
  {
    id: 'c-2',
    title: 'Starter plan price changed',
    description: 'Price updated from ৳800 to ৳1,000',
    timeAgo: '1 day ago',
    iconType: 'price',
  },
  {
    id: 'c-3',
    title: 'Enterprise plan created',
    description: 'New enterprise plan with advanced features',
    timeAgo: '3 days ago',
    iconType: 'create',
  },
];
