import {
  PlanKpiItem,
  PlanRecord,
  PlanDonutItem,
  PlanHighlightItem,
  PlanRecentChangeItem,
} from './types';

export const PLANS_KPIS: PlanKpiItem[] = [
  {
    id: 'total-plans',
    title: 'Total Plans',
    value: '5',
    subtext: 'Active plans',
    iconType: 'total',
  },
  {
    id: 'active-plans',
    title: 'Active Plans',
    value: '4',
    subtext: 'Visible to merchants',
    iconType: 'active',
  },
  {
    id: 'inactive-plans',
    title: 'Inactive Plans',
    value: '1',
    subtext: 'Not visible to merchants',
    iconType: 'inactive',
  },
  {
    id: 'most-popular',
    title: 'Most Popular Plan',
    value: 'Growth',
    subtext: '842 merchants',
    iconType: 'popular',
  },
  {
    id: 'mrr',
    title: 'MRR (Monthly)',
    value: '৳18,40,000',
    subtext: 'From all active plans',
    iconType: 'mrr',
  },
];

export const INITIAL_PLANS: PlanRecord[] = [
  {
    id: 'plan-starter',
    name: 'Starter',
    subtitle: 'Perfect for new businesses',
    featuresCountText: '8 features',
    iconType: 'starter',
    iconBg: 'bg-emerald-600',
    price: '৳1,000',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    merchantsCount: '1,240',
    merchantsShare: '(48.7%)',
    mrr: '৳12,40,000',
    mrrShare: '(24.8%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    description: 'Perfect for new merchants who are just getting started.',
    featuresUsed: 8,
    featuresTotal: 50,
  },
  {
    id: 'plan-growth',
    name: 'Growth',
    subtitle: 'For growing businesses',
    featuresCountText: '18 features',
    iconType: 'growth',
    iconBg: 'bg-blue-600',
    price: '৳2,500',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    merchantsCount: '842',
    merchantsShare: '(33.1%)',
    mrr: '৳9,80,000',
    mrrShare: '(19.6%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    description: 'Ideal for scaling stores requiring more inventory and staff accounts.',
    featuresUsed: 18,
    featuresTotal: 50,
  },
  {
    id: 'plan-business',
    name: 'Business',
    subtitle: 'Advanced for scaling teams',
    featuresCountText: '28 features',
    iconType: 'business',
    iconBg: 'bg-amber-500',
    price: '৳5,000',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    merchantsCount: '328',
    merchantsShare: '(12.9%)',
    mrr: '৳5,00,000',
    mrrShare: '(10.0%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    description: 'Tailored for high-volume retailers needing API and ERP integrations.',
    featuresUsed: 28,
    featuresTotal: 50,
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise',
    subtitle: 'For large scale enterprises',
    featuresCountText: '40+ features',
    iconType: 'enterprise',
    iconBg: 'bg-purple-600',
    price: '৳10,000',
    billingPeriod: '/ month',
    billingCycle: 'Monthly',
    merchantsCount: '56',
    merchantsShare: '(2.2%)',
    mrr: '৳56,000',
    mrrShare: '(1.1%)',
    status: 'Active',
    createdAt: {
      date: 'Jul 10, 2026',
      time: '10:30 AM',
    },
    description: 'Dedicated infrastructure, SLA support, and infinite scalability.',
    featuresUsed: 42,
    featuresTotal: 50,
  },
  {
    id: 'plan-custom',
    name: 'Custom',
    subtitle: 'Custom plan for specific needs',
    featuresCountText: 'Custom features',
    iconType: 'custom',
    iconBg: 'bg-slate-500',
    price: 'Custom',
    billingPeriod: '/ month',
    billingCycle: 'Custom',
    merchantsCount: '-',
    merchantsShare: '(0%)',
    mrr: '৳0',
    mrrShare: '(0%)',
    status: 'Inactive',
    createdAt: {
      date: 'Jun 15, 2026',
      time: '02:15 PM',
    },
    description: 'Bespoke configuration designed with our enterprise solutions team.',
    featuresUsed: 15,
    featuresTotal: 50,
  },
];

export const PLAN_DONUT_DATA: PlanDonutItem[] = [
  { name: 'Starter', value: 1240, percentage: '48.7%', color: '#10B981' },
  { name: 'Growth', value: 842, percentage: '33.1%', color: '#3B82F6' },
  { name: 'Business', value: 328, percentage: '12.9%', color: '#F59E0B' },
  { name: 'Enterprise', value: 56, percentage: '2.2%', color: '#8B5CF6' },
  { name: 'Custom', value: 118, percentage: '4.6%', color: '#64748B' },
];

export const PLAN_HIGHLIGHTS: PlanHighlightItem[] = [
  {
    id: 'h-1',
    tag: 'Highest MRR',
    planName: 'Growth Plan',
    statValue: '৳9,80,000 / month',
    tagColor: 'green',
  },
  {
    id: 'h-2',
    tag: 'Most Merchants',
    planName: 'Starter Plan',
    statValue: '1,240 merchants',
    tagColor: 'blue',
  },
  {
    id: 'h-3',
    tag: 'Highest ARPU',
    planName: 'Business Plan',
    statValue: '৳15,244 / month',
    tagColor: 'amber',
  },
  {
    id: 'h-4',
    tag: 'Best Conversion',
    planName: 'Growth Plan',
    statValue: '23.5% conversion',
    tagColor: 'purple',
  },
];

export const PLAN_RECENT_CHANGES: PlanRecentChangeItem[] = [
  {
    id: 'c-1',
    title: 'Business plan updated',
    description: 'Updated features and limits',
    timeAgo: '2 hours ago',
    iconType: 'edit',
  },
  {
    id: 'c-2',
    title: 'Starter plan price changed',
    description: 'Price updated from ৳800 to ৳1,000',
    timeAgo: '1 day ago',
    iconType: 'price',
  },
  {
    id: 'c-3',
    title: 'Enterprise plan created',
    description: 'New enterprise plan with advanced features',
    timeAgo: '3 days ago',
    iconType: 'create',
  },
];
