import {
  TicketRecord,
  SupportKpiMetric,
  CategorySummary,
  SlaMetric,
} from './types';

export const SUPPORT_KPIS: SupportKpiMetric[] = [
  {
    id: 'kpi-total',
    title: 'Total Tickets',
    value: '1,248',
    change: '+18.6%',
    isPositive: true,
    periodText: 'vs last 7 days',
    type: 'total',
  },
  {
    id: 'kpi-open',
    title: 'Open',
    value: '236',
    change: '+12.4%',
    isPositive: true,
    periodText: 'vs last 7 days',
    type: 'open',
  },
  {
    id: 'kpi-in-progress',
    title: 'In Progress',
    value: '158',
    change: '+8.3%',
    isPositive: true,
    periodText: 'vs last 7 days',
    type: 'in_progress',
  },
  {
    id: 'kpi-pending',
    title: 'Pending Merchant',
    value: '312',
    change: '-4.6%',
    isPositive: false,
    periodText: 'vs last 7 days',
    type: 'pending',
  },
  {
    id: 'kpi-resolved',
    title: 'Resolved',
    value: '542',
    change: '+22.7%',
    isPositive: true,
    periodText: 'vs last 7 days',
    type: 'resolved',
  },
];

export const TOP_CATEGORIES: CategorySummary[] = [
  {
    id: 'cat-billing',
    name: 'Billing & Payments',
    count: 342,
    iconName: 'CreditCard',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
  },
  {
    id: 'cat-account',
    name: 'Account & Access',
    count: 256,
    iconName: 'UserCheck',
    color: '#F59E0B',
    bgColor: '#FFFBEB',
  },
  {
    id: 'cat-tech',
    name: 'Technical Issues',
    count: 198,
    iconName: 'Cpu',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
  },
  {
    id: 'cat-store',
    name: 'Store Management',
    count: 172,
    iconName: 'Store',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
  },
  {
    id: 'cat-features',
    name: 'Feature Requests',
    count: 128,
    iconName: 'Lightbulb',
    color: '#EC4899',
    bgColor: '#FDF2F8',
  },
];

export const SLA_METRICS: SlaMetric[] = [
  {
    title: 'Response Time',
    value: '2h 34m',
    subtitle: 'Avg. First Response',
  },
  {
    title: 'Resolution Time',
    value: '18h 42m',
    subtitle: 'Avg. Resolution',
  },
  {
    title: 'SLA Met',
    value: '92.3%',
    subtitle: 'Tickets',
  },
];

export const INITIAL_TICKETS: TicketRecord[] = [
  {
    id: 'tkt-1',
    codeId: 'TKT-2026-001248',
    createdAt: 'Aug 14, 2026',
    createdTime: '10:32 AM',
    subject: 'Unable to upgrade my plan',
    category: 'Plan & Billing',
    categoryDetail: 'Plan & Billing',
    subCategory: 'Plan Upgrade Issue',
    sourceIP: '103.86.XXX.XXX',
    merchant: {
      id: 'm-1',
      merchantCode: 'MRC-2026-000112',
      name: 'Rahim Hossain',
      email: 'rahim.hossain@email.com',
      storeName: 'Urban Style Store',
      subdomain: 'urbstyle.easyco.com',
      plan: 'Growth',
      initials: 'U',
      phone: '+880 1712-345678',
      location: 'Dhaka, Bangladesh',
    },
    priority: 'High',
    status: 'Open',
    lastUpdateDate: 'Aug 14, 2026',
    lastUpdateTime: '10:32 AM',
    channel: 'Web',
    assignedAgent: {
      name: 'Sadia Ahmed',
      role: 'Support Agent',
      email: 'sadia.ahmed@easycommerce.com',
      initials: 'SA',
    },
    sla: {
      responseTime: 'Within 2h',
      firstResponse: '32m (Met)',
      resolutionTime: 'Within 24h',
      timeRemaining: '18h 42m',
      isMet: true,
    },
    description:
      'I am trying to upgrade my Growth Plan to Business Plan, but it is not working. After clicking the upgrade button, I got an error message "Payment failed". But the amount was deducted from my card.',
    messages: [
      {
        id: 'msg-1',
        authorName: 'Rahim Hossain (Merchant)',
        authorRole: 'Merchant',
        authorSubtitle: 'urbanstyle.easyco.com',
        authorInitials: 'RH',
        content: `Hi,\nI'm trying to upgrade my Growth Plan to Business Plan, but it's not working. After clicking the upgrade button, I got an error message "Payment failed". But the amount was deducted from my card.\nPlease help me resolve this issue.\n\nThanks`,
        timestamp: 'Aug 14, 2026 10:32 AM',
      },
      {
        id: 'msg-2',
        authorName: 'Sadia Ahmed (Agent)',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'SA',
        isCurrentUser: true,
        content: `Hello Rahim,\nThank you for contacting us. I'm sorry for the inconvenience. I have checked your account and found that the payment was not completed due to a temporary gateway issue.\n\nPlease try upgrading again. If the amount was deducted, it will be automatically refunded within 3–5 business days.\n\nLet me know if you face any further issues.`,
        timestamp: 'Aug 14, 2026 10:47 AM',
      },
      {
        id: 'msg-3',
        authorName: 'Rahim Hossain (Merchant)',
        authorRole: 'Merchant',
        authorSubtitle: 'urbanstyle.easyco.com',
        authorInitials: 'RH',
        content: `Thanks for the update. I tried again and it worked. Please confirm if the previous deduction will be refunded.`,
        timestamp: 'Aug 14, 2026 11:05 AM',
      },
      {
        id: 'msg-4',
        authorName: 'Sadia Ahmed (Agent)',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'SA',
        isCurrentUser: true,
        content: `Yes, the previous deduction of ৳5,000.00 will be refunded to your card within 3–5 business days. You will receive an email once the refund is processed.`,
        timestamp: 'Aug 14, 2026 11:12 AM',
      },
    ],
    internalNotes: [
      {
        id: 'note-1',
        authorName: 'Sadia Ahmed',
        authorRole: 'Agent',
        authorInitials: 'SA',
        isInternal: true,
        content:
          'Gateway log shows timeout from City Bank SSLCommerz node. Attempted retry succeeded on merchant end. Initiating auto-reconciliation request with finance team.',
        timestamp: 'Aug 14, 2026 10:40 AM',
      },
      {
        id: 'note-2',
        authorName: 'Alex Rivera',
        authorRole: 'Admin',
        authorInitials: 'AR',
        isInternal: true,
        content:
          'Verified gateway settlement queue. Refund batch #REF-99201 scheduled for 4:00 PM batch run.',
        timestamp: 'Aug 14, 2026 11:00 AM',
      },
    ],
    attachments: [
      {
        id: 'att-1',
        name: 'payment_failed_screenshot.png',
        size: '1.2 MB',
        type: 'image/png',
        uploadedBy: 'Rahim Hossain',
        uploadedAt: 'Aug 14, 2026 10:32 AM',
      },
      {
        id: 'att-2',
        name: 'bank_statement_deduction.pdf',
        size: '450 KB',
        type: 'application/pdf',
        uploadedBy: 'Rahim Hossain',
        uploadedAt: 'Aug 14, 2026 10:32 AM',
      },
      {
        id: 'att-3',
        name: 'transaction_log_8AK39921.txt',
        size: '42 KB',
        type: 'text/plain',
        uploadedBy: 'Sadia Ahmed',
        uploadedAt: 'Aug 14, 2026 10:45 AM',
      },
    ],
    activityLogs: [
      {
        id: 'act-1',
        action: 'Ticket Created',
        actor: 'Rahim Hossain (Merchant)',
        timestamp: 'Aug 14, 2026 10:32 AM',
        details: 'Submitted via Web Portal (Source IP: 103.86.XXX.XXX)',
      },
      {
        id: 'act-2',
        action: 'Assigned Agent',
        actor: 'System Auto-Router',
        timestamp: 'Aug 14, 2026 10:33 AM',
        details: 'Assigned to Sadia Ahmed (Billing Team)',
      },
      {
        id: 'act-3',
        action: 'First Response Sent',
        actor: 'Sadia Ahmed',
        timestamp: 'Aug 14, 2026 10:47 AM',
        details: 'SLA Met (First response delivered in 32m)',
      },
      {
        id: 'act-4',
        action: 'Internal Note Added',
        actor: 'Alex Rivera',
        timestamp: 'Aug 14, 2026 11:00 AM',
        details: 'Added note regarding refund batch settlement',
      },
    ],
    relatedTickets: [
      {
        id: 'rel-1',
        codeId: 'TKT-2026-000842',
        subject: 'Plan downgrade inquiry and billing cycle adjustment',
        status: 'Resolved',
        priority: 'Low',
        createdAt: 'Jul 10, 2026',
      },
    ],
  },
  {
    id: 'tkt-2',
    codeId: 'TKT-2026-001247',
    createdAt: 'Aug 14, 2026',
    createdTime: '09:17 AM',
    subject: 'Payment failed but amount deducted',
    category: 'Billing & Payments',
    categoryDetail: 'Payment Issue',
    subCategory: 'bKash Gateway Trx Failure',
    sourceIP: '103.112.YYY.YYY',
    merchant: {
      id: 'm-2',
      merchantCode: 'MRC-2026-000108',
      name: 'Nusrat Jahan',
      email: 'nusrat@abcfashion.com',
      storeName: 'ABC Fashion Store',
      subdomain: 'abcfashion.easyco.com',
      plan: 'Business',
      initials: 'A',
      phone: '+880 1812-334455',
      location: 'Chittagong, Bangladesh',
    },
    priority: 'High',
    status: 'In Progress',
    lastUpdateDate: 'Aug 14, 2026',
    lastUpdateTime: '09:17 AM',
    channel: 'Email',
    assignedAgent: {
      name: 'Alex Rivera',
      role: 'Platform Engineer',
      email: 'alex.r@easycommerce.com',
      initials: 'AR',
    },
    sla: {
      responseTime: 'Within 2h',
      firstResponse: '17m (Met)',
      resolutionTime: 'Within 24h',
      timeRemaining: '16h 20m',
      isMet: true,
    },
    description:
      'Customer order #ORD-99321 transaction failed on bKash but ৳3,450 was debited from user wallet.',
    messages: [
      {
        id: 'msg-201',
        authorName: 'Nusrat Jahan',
        authorRole: 'Merchant',
        authorSubtitle: 'abcfashion.easyco.com',
        authorInitials: 'NJ',
        content:
          'One of our regular shoppers completed payment of ৳3,450 via bKash gateway. The money was deducted from her account, but our dashboard marks the order as Abandoned/Failed. Attached the bKash TrxID #8AK39921.',
        timestamp: 'Aug 14, 2026, 09:00 AM',
      },
      {
        id: 'msg-202',
        authorName: 'Alex Rivera',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'AR',
        isCurrentUser: true,
        content:
          'Hi Nusrat, thank you for reaching out. We have received the TrxID and our financial reconciliation team is verifying the webhook logs with bKash API. We will update you in 30 minutes.',
        timestamp: 'Aug 14, 2026, 09:17 AM',
      },
    ],
  },
  {
    id: 'tkt-3',
    codeId: 'TKT-2026-001246',
    createdAt: 'Aug 13, 2026',
    createdTime: '05:45 PM',
    subject: 'Custom domain not working',
    category: 'Domain & SSL',
    categoryDetail: 'Domain & SSL',
    subCategory: 'SSL Handshake Failure',
    sourceIP: '103.204.ZZZ.ZZZ',
    merchant: {
      id: 'm-3',
      merchantCode: 'MRC-2026-000095',
      name: 'Tanvir Ahmed',
      email: 'tanvir@gadgethub.com',
      storeName: 'Gadget Hub',
      subdomain: 'gadgethub.easyco.com',
      plan: 'Business',
      initials: 'G',
      phone: '+880 1913-667788',
      location: 'Sylhet, Bangladesh',
    },
    priority: 'Medium',
    status: 'Pending Merchant',
    lastUpdateDate: 'Aug 13, 2026',
    lastUpdateTime: '05:45 PM',
    channel: 'Web',
    assignedAgent: {
      name: 'David Miller',
      role: 'Security & DevOps',
      email: 'david.m@easycommerce.com',
      initials: 'DM',
    },
    sla: {
      responseTime: 'Within 4h',
      firstResponse: '1h 12m (Met)',
      resolutionTime: 'Within 48h',
      timeRemaining: '28h 15m',
      isMet: true,
    },
    description: 'SSL certificate handshake failing for custom domain gadgethub.com.bd',
    messages: [
      {
        id: 'msg-301',
        authorName: 'Tanvir Ahmed',
        authorRole: 'Merchant',
        authorSubtitle: 'gadgethub.easyco.com',
        authorInitials: 'TA',
        content:
          'We added CNAME records for gadgethub.com.bd 24 hours ago, but visitors are getting "SSL Handshake Failed (ERR_SSL_PROTOCOL_ERROR)".',
        timestamp: 'Aug 13, 2026, 02:15 PM',
      },
      {
        id: 'msg-302',
        authorName: 'David Miller',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'DM',
        isCurrentUser: true,
        content:
          'Hello Tanvir, we checked your DNS propagation. It seems there is an old conflicting A record (IP 192.0.2.1) in your Cloudflare panel. Please delete that A record so our Let\'s Encrypt auto-provisioner can issue the cert.',
        timestamp: 'Aug 13, 2026, 05:45 PM',
      },
    ],
  },
  {
    id: 'tkt-4',
    codeId: 'TKT-2026-001245',
    createdAt: 'Aug 13, 2026',
    createdTime: '04:21 PM',
    subject: 'Store not visible on platform',
    category: 'Store Management',
    categoryDetail: 'Store Management',
    subCategory: 'Maintenance Mode Bypass',
    sourceIP: '103.88.AAA.AAA',
    merchant: {
      id: 'm-4',
      merchantCode: 'MRC-2026-000084',
      name: 'Farhana Yasmin',
      email: 'farhana@bookhaven.com',
      storeName: 'Book Haven',
      subdomain: 'bookhaven.easyco.com',
      plan: 'Growth',
      initials: 'B',
      phone: '+880 1614-223344',
      location: 'Dhaka, Bangladesh',
    },
    priority: 'Medium',
    status: 'Open',
    lastUpdateDate: 'Aug 13, 2026',
    lastUpdateTime: '04:21 PM',
    channel: 'Chat',
    assignedAgent: {
      name: 'Sadia Ahmed',
      role: 'Support Agent',
      email: 'sadia.ahmed@easycommerce.com',
      initials: 'SA',
    },
    sla: {
      responseTime: 'Within 2h',
      firstResponse: 'Pending',
      resolutionTime: 'Within 24h',
      timeRemaining: '22h 39m',
      isMet: true,
    },
    description: 'Storefront shows 404 Maintenance mode even after toggling Live switch in settings.',
    messages: [
      {
        id: 'msg-401',
        authorName: 'Farhana Yasmin',
        authorRole: 'Merchant',
        authorSubtitle: 'bookhaven.easyco.com',
        authorInitials: 'FY',
        content:
          'Hi! We activated our store in the admin settings earlier, but visitors still see "Store Under Maintenance". Could you please flush the CDN cache for our store domain?',
        timestamp: 'Aug 13, 2026, 04:21 PM',
      },
    ],
  },
  {
    id: 'tkt-5',
    codeId: 'TKT-2026-001244',
    createdAt: 'Aug 13, 2026',
    createdTime: '02:11 PM',
    subject: 'Need help with product import',
    category: 'Product Management',
    categoryDetail: 'Product Management',
    subCategory: 'CSV Bulk Upload Format',
    sourceIP: '103.74.BBB.BBB',
    merchant: {
      id: 'm-5',
      merchantCode: 'MRC-2026-000072',
      name: 'Kazi Masud',
      email: 'kazi@dailyessentials.com',
      storeName: 'Daily Essentials',
      subdomain: 'dailyessentials.easyco.com',
      plan: 'Starter',
      initials: 'D',
      phone: '+880 1515-778899',
      location: 'Rajshahi, Bangladesh',
    },
    priority: 'Low',
    status: 'In Progress',
    lastUpdateDate: 'Aug 13, 2026',
    lastUpdateTime: '02:11 PM',
    channel: 'Email',
    assignedAgent: {
      name: 'Alex Rivera',
      role: 'Platform Engineer',
      email: 'alex.r@easycommerce.com',
      initials: 'AR',
    },
    sla: {
      responseTime: 'Within 8h',
      firstResponse: '2h 41m (Met)',
      resolutionTime: 'Within 48h',
      timeRemaining: '38h 10m',
      isMet: true,
    },
    description: 'CSV bulk upload error on row 42: "Invalid variant SKU format".',
    messages: [
      {
        id: 'msg-501',
        authorName: 'Kazi Masud',
        authorRole: 'Merchant',
        authorSubtitle: 'dailyessentials.easyco.com',
        authorInitials: 'KM',
        content:
          'We are trying to import 500 grocery SKUs via the CSV template. The import halts at row 42 with an unhandled exception. Attached the CSV file.',
        timestamp: 'Aug 13, 2026, 11:30 AM',
      },
      {
        id: 'msg-502',
        authorName: 'Alex Rivera',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'AR',
        isCurrentUser: true,
        content:
          'Hello Kazi, we reviewed row 42. It has a special non-UTF8 character in the price column. We sanitized the file and re-imported 480 rows successfully. Please review the remaining 20 rows.',
        timestamp: 'Aug 13, 2026, 02:11 PM',
      },
    ],
  },
  {
    id: 'tkt-6',
    codeId: 'TKT-2026-001243',
    createdAt: 'Aug 12, 2026',
    createdTime: '11:20 AM',
    subject: 'Refund has not been received',
    category: 'Refund & Payout',
    categoryDetail: 'Refund & Payout',
    subCategory: 'BEFTN Payout Delay',
    sourceIP: '103.95.CCC.CCC',
    merchant: {
      id: 'm-6',
      merchantCode: 'MRC-2026-000061',
      name: 'Shahriar Kabir',
      email: 'shahriar@techsolution.com',
      storeName: 'Tech Solution',
      subdomain: 'techsolution.easyco.com',
      plan: 'Business',
      initials: 'T',
      phone: '+880 1718-990011',
      location: 'Dhaka, Bangladesh',
    },
    priority: 'High',
    status: 'Pending Merchant',
    lastUpdateDate: 'Aug 12, 2026',
    lastUpdateTime: '11:20 AM',
    channel: 'Web',
    assignedAgent: {
      name: 'David Miller',
      role: 'Security & DevOps',
      email: 'david.m@easycommerce.com',
      initials: 'DM',
    },
    sla: {
      responseTime: 'Within 2h',
      firstResponse: '1h 40m (Met)',
      resolutionTime: 'Within 24h',
      timeRemaining: '12h 05m',
      isMet: true,
    },
    description: 'Merchant requested payout adjustment of ৳75,000 for canceled billing cycle.',
    messages: [
      {
        id: 'msg-601',
        authorName: 'Shahriar Kabir',
        authorRole: 'Merchant',
        authorSubtitle: 'techsolution.easyco.com',
        authorInitials: 'SK',
        content:
          'We initiated a refund request on August 5th for the duplicate addon charge. It has been 7 business days and the funds have not settled to our Dutch-Bangla Bank account.',
        timestamp: 'Aug 12, 2026, 09:40 AM',
      },
      {
        id: 'msg-602',
        authorName: 'David Miller',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'DM',
        isCurrentUser: true,
        content:
          'Hello Shahriar, our accounts department processed the BEFTN transfer with reference #DBBL-9920194. Please check with your bank branch using this ARN number and let us know if you need an official bank confirmation slip.',
        timestamp: 'Aug 12, 2026, 11:20 AM',
      },
    ],
  },
  {
    id: 'tkt-7',
    codeId: 'TKT-2026-001242',
    createdAt: 'Aug 12, 2026',
    createdTime: '08:33 AM',
    subject: 'Unable to login to my account',
    category: 'Account & Access',
    categoryDetail: 'Account & Access',
    subCategory: '2FA SMS Failure',
    sourceIP: '103.62.DDD.DDD',
    merchant: {
      id: 'm-7',
      merchantCode: 'MRC-2026-000050',
      name: 'Mehedi Hasan',
      email: 'mehedi@homemart.com',
      storeName: 'Home Mart',
      subdomain: 'homemart.easyco.com',
      plan: 'Growth',
      initials: 'H',
      phone: '+880 1819-445566',
      location: 'Khulna, Bangladesh',
    },
    priority: 'Medium',
    status: 'Resolved',
    lastUpdateDate: 'Aug 12, 2026',
    lastUpdateTime: '08:33 AM',
    channel: 'Chat',
    assignedAgent: {
      name: 'Sadia Ahmed',
      role: 'Support Agent',
      email: 'sadia.ahmed@easycommerce.com',
      initials: 'SA',
    },
    sla: {
      responseTime: 'Within 2h',
      firstResponse: '23m (Met)',
      resolutionTime: 'Within 24h',
      timeRemaining: 'Resolved',
      isMet: true,
    },
    description: '2FA authentication OTP not reaching phone number on login attempt.',
    messages: [
      {
        id: 'msg-701',
        authorName: 'Mehedi Hasan',
        authorRole: 'Merchant',
        authorSubtitle: 'homemart.easyco.com',
        authorInitials: 'MH',
        content:
          'I am locked out because SMS OTP is not delivering to my phone (+880 1819-445566). Can you reset my 2FA or send backup codes to my registered email?',
        timestamp: 'Aug 12, 2026, 08:10 AM',
      },
      {
        id: 'msg-702',
        authorName: 'Sadia Ahmed',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'SA',
        isCurrentUser: true,
        content:
          'Hello Mehedi, we verified your identity using your security questions and sent a one-time 2FA recovery link to your verified email mehedi@homemart.com. This ticket is now resolved.',
        timestamp: 'Aug 12, 2026, 08:33 AM',
      },
    ],
  },
  {
    id: 'tkt-8',
    codeId: 'TKT-2026-001241',
    createdAt: 'Aug 12, 2026',
    createdTime: '07:12 AM',
    subject: 'Feature request: Bulk discount',
    category: 'Feature Requests',
    categoryDetail: 'Feature Request',
    subCategory: 'Promotions Tier Rules',
    sourceIP: '103.55.EEE.EEE',
    merchant: {
      id: 'm-8',
      merchantCode: 'MRC-2026-000039',
      name: 'Anika Tabassum',
      email: 'anika@freshshop.com',
      storeName: 'FreshShop',
      subdomain: 'freshshop.easyco.com',
      plan: 'Starter',
      initials: 'F',
      phone: '+880 1912-889900',
      location: 'Dhaka, Bangladesh',
    },
    priority: 'Low',
    status: 'Resolved',
    lastUpdateDate: 'Aug 12, 2026',
    lastUpdateTime: '07:12 AM',
    channel: 'Web',
    assignedAgent: {
      name: 'Alex Rivera',
      role: 'Platform Engineer',
      email: 'alex.r@easycommerce.com',
      initials: 'AR',
    },
    sla: {
      responseTime: 'Within 24h',
      firstResponse: '27m (Met)',
      resolutionTime: 'Within 72h',
      timeRemaining: 'Resolved',
      isMet: true,
    },
    description: 'Requesting tiered volume discount rules per customer tag in checkout.',
    messages: [
      {
        id: 'msg-801',
        authorName: 'Anika Tabassum',
        authorRole: 'Merchant',
        authorSubtitle: 'freshshop.easyco.com',
        authorInitials: 'AT',
        content:
          'We would love to see a native feature to offer tiered quantity discounts (e.g. Buy 3 get 10% off, Buy 5 get 20% off) without needing third-party script tags.',
        timestamp: 'Aug 12, 2026, 06:45 AM',
      },
      {
        id: 'msg-802',
        authorName: 'Alex Rivera',
        authorRole: 'Agent',
        authorSubtitle: 'EasyCommerce Support',
        authorInitials: 'AR',
        isCurrentUser: true,
        content:
          'Hi Anika, thank you for the valuable feedback! We have added this to our Q4 roadmap for the Promotions engine (Ref: PROMO-1049). We will notify you once beta testing opens.',
        timestamp: 'Aug 12, 2026, 07:12 AM',
      },
    ],
  },
];
